// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Core.Storagezone.Checkavailability;
using Soenneker.Bunny.OpenApiClient.Core.Storagezone.Item;
using Soenneker.Bunny.OpenApiClient.Core.Storagezone.Regions;
using Soenneker.Bunny.OpenApiClient.Core.Storagezone.ResetReadOnlyPassword;
using Soenneker.Bunny.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bunny.OpenApiClient.Core.Storagezone
{
    /// <summary>
    /// Builds and executes requests for operations under \core\storagezone
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StoragezoneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The checkavailability property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Checkavailability.CheckavailabilityRequestBuilder Checkavailability
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Checkavailability.CheckavailabilityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The regions property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Regions.RegionsRequestBuilder Regions
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Regions.RegionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetReadOnlyPassword property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.ResetReadOnlyPassword.ResetReadOnlyPasswordRequestBuilder ResetReadOnlyPassword
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.ResetReadOnlyPassword.ResetReadOnlyPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.core.storagezone.item collection</summary>
        /// <param name="position">The ID of the Storage Zone that should be returned</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Item.StoragezoneItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Item.StoragezoneItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.Item.StoragezoneItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoragezoneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/storagezone{?includeDeleted*,page*,perPage*,search*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoragezoneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core/storagezone{?includeDeleted*,page*,perPage*,search*}", rawUrl)
        {
        }
        /// <summary>
        /// List Storage Zones
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel>> GetAsync(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel>(requestInfo, global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Add Storage Zone
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bunny.OpenApiClient.Models.ApiErrorData">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel?> PostAsync(global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModelAdd body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel> PostAsync(global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModelAdd body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Bunny.OpenApiClient.Models.ApiErrorData.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel>(requestInfo, global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List Storage Zones
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder.StoragezoneRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add Storage Zone
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModelAdd body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bunny.OpenApiClient.Models.StorageZoneModelAdd body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// List Storage Zones
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class StoragezoneRequestBuilderGetQueryParameters 
        {
            [QueryParameter("includeDeleted")]
            public bool? IncludeDeleted { get; set; }
            /// <summary>The page number to return. When set to 0 (default), all items are returned as a plain array. When set to a value greater than 0, items are returned in a paginated response object.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("perPage")]
            public int? PerPage { get; set; }
            /// <summary>The search term that will be used to filter the results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
