// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Core.Apikey;
using Soenneker.Bunny.OpenApiClient.Core.Billing;
using Soenneker.Bunny.OpenApiClient.Core.Country;
using Soenneker.Bunny.OpenApiClient.Core.Dnszone;
using Soenneker.Bunny.OpenApiClient.Core.Loadbalancer;
using Soenneker.Bunny.OpenApiClient.Core.Pullzone;
using Soenneker.Bunny.OpenApiClient.Core.Purge;
using Soenneker.Bunny.OpenApiClient.Core.Region;
using Soenneker.Bunny.OpenApiClient.Core.Search;
using Soenneker.Bunny.OpenApiClient.Core.Statistics;
using Soenneker.Bunny.OpenApiClient.Core.Storagezone;
using Soenneker.Bunny.OpenApiClient.Core.User;
using Soenneker.Bunny.OpenApiClient.Core.Videolibrary;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.Core
{
    /// <summary>
    /// Builds and executes requests for operations under \core
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CoreRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apikey property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Apikey.ApikeyRequestBuilder Apikey
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Apikey.ApikeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The billing property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Billing.BillingRequestBuilder Billing
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Billing.BillingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The country property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Country.CountryRequestBuilder Country
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Country.CountryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dnszone property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Dnszone.DnszoneRequestBuilder Dnszone
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Dnszone.DnszoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The loadbalancer property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Loadbalancer.LoadbalancerRequestBuilder Loadbalancer
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Loadbalancer.LoadbalancerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pullzone property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Pullzone.PullzoneRequestBuilder Pullzone
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Pullzone.PullzoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The purge property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Purge.PurgeRequestBuilder Purge
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Purge.PurgeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The region property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Region.RegionRequestBuilder Region
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Region.RegionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statistics property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Statistics.StatisticsRequestBuilder Statistics
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Statistics.StatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storagezone property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder Storagezone
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Storagezone.StoragezoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The videolibrary property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Core.Videolibrary.VideolibraryRequestBuilder Videolibrary
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Core.Videolibrary.VideolibraryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Core.CoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoreRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Core.CoreRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CoreRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/core", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
