// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\metrics\shield-zone\{shieldZoneId}\waf-rule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WafRuleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.shield.metrics.shieldZone.item.wafRule.item collection</summary>
        /// <param name="position">The ID of the WAF Rule.</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.Item.WithRuleItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.Item.WithRuleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("ruleId", position);
                return new global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.Item.WithRuleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.WafRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WafRuleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/shield-zone/{shieldZoneId}/waf-rule", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.WafRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WafRuleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/shield-zone/{shieldZoneId}/waf-rule", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
