// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.Active;
using Soenneker.Bunny.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases
{
    /// <summary>
    /// Builds and executes requests for operations under \edge-scripting\compute\script\{id}\releases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReleasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.Active.ActiveRequestBuilder Active
        {
            get => new global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/edge-scripting/compute/script/{id}/releases{?page*,perPage*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/edge-scripting/compute/script/{id}/releases{?page*,perPage*}", rawUrl)
        {
        }
        /// <summary>
        /// Get Releases
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.PaginationListModelOfEdgeScriptReleaseModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.PaginationListModelOfEdgeScriptReleaseModel?> GetAsync(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder.ReleasesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.PaginationListModelOfEdgeScriptReleaseModel> GetAsync(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder.ReleasesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Bunny.OpenApiClient.Models.PaginationListModelOfEdgeScriptReleaseModel>(requestInfo, global::Soenneker.Bunny.OpenApiClient.Models.PaginationListModelOfEdgeScriptReleaseModel.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Releases
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder.ReleasesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder.ReleasesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bunny.OpenApiClient.EdgeScripting.Compute.Script.Item.Releases.ReleasesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Releases
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReleasesRequestBuilderGetQueryParameters 
        {
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("perPage")]
            public int? PerPage { get; set; }
        }
    }
}
#pragma warning restore CS0618
