// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.MagicContainers.Log.Forwarding;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.MagicContainers.Log
{
    /// <summary>
    /// Builds and executes requests for operations under \magic-containers\log
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The forwarding property</summary>
        public global::Soenneker.Bunny.OpenApiClient.MagicContainers.Log.Forwarding.ForwardingRequestBuilder Forwarding
        {
            get => new global::Soenneker.Bunny.OpenApiClient.MagicContainers.Log.Forwarding.ForwardingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.MagicContainers.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/magic-containers/log", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.MagicContainers.Log.LogRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/magic-containers/log", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
