// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances
{
    /// <summary>
    /// Builds and executes requests for operations under \magic-containers\apps\{appId}\volumes\{volumeId}\instances
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InstancesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.magicContainers.apps.item.volumes.item.instances.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.Item.WithInstanceItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.Item.WithInstanceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("instanceId", position);
                return new global::Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.Item.WithInstanceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.InstancesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstancesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/magic-containers/apps/{appId}/volumes/{volumeId}/instances", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.MagicContainers.Apps.Item.Volumes.Item.Instances.InstancesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InstancesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/magic-containers/apps/{appId}/volumes/{volumeId}/instances", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
