// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.ApiGuardian;
using Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.BotDetection;
using Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.UploadScanning;
using Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\metrics\shield-zone\{shieldZoneId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithShieldZoneItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apiGuardian property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.ApiGuardian.ApiGuardianRequestBuilder ApiGuardian
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.ApiGuardian.ApiGuardianRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The botDetection property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.BotDetection.BotDetectionRequestBuilder BotDetection
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.BotDetection.BotDetectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The uploadScanning property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.UploadScanning.UploadScanningRequestBuilder UploadScanning
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.UploadScanning.UploadScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wafRule property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.WafRuleRequestBuilder WafRule
        {
            get => new global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WafRule.WafRuleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShieldZoneItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/shield-zone/{shieldZoneId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Metrics.ShieldZone.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShieldZoneItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/metrics/shield-zone/{shieldZoneId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
