// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\event-logs\{shieldZoneId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithShieldZoneItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.shield.eventLogs.item.item collection</summary>
        /// <param name="position">The Date (MM-dd-yyyy) of returned Event Logs.</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.Item.WithDateItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.Item.WithDateItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("date", position);
                return new global::Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.Item.WithDateItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShieldZoneItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/event-logs/{shieldZoneId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.EventLogs.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShieldZoneItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/event-logs/{shieldZoneId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
