// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.Models;
using Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\waf\custom-rule
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomRuleRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.shield.waf.customRule.item collection</summary>
        /// <param name="position">The ID of the Custom WAF Rule.</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.Item.CustomRuleItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.Item.CustomRuleItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.Item.CustomRuleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.CustomRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomRuleRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/waf/custom-rule", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.CustomRuleRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomRuleRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/shield/waf/custom-rule", rawUrl)
        {
        }
        /// <summary>
        /// Create a new custom WAF rule
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.CustomWafRule"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Bunny.OpenApiClient.Models.UnauthorizedResult">When receiving a 401 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.CustomWafRule?> PostAsync(global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Bunny.OpenApiClient.Models.CustomWafRule> PostAsync(global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Bunny.OpenApiClient.Models.UnauthorizedResult.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Bunny.OpenApiClient.Models.CustomWafRule>(requestInfo, global::Soenneker.Bunny.OpenApiClient.Models.CustomWafRule.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new custom WAF rule
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.CustomRuleRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.CustomRuleRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Bunny.OpenApiClient.Shield.Waf.CustomRule.CustomRuleRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
