// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.OriginErrors.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.OriginErrors.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \origin-errors\{pullZoneId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPullZoneItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Bunny.OpenApiClient.originErrors.item.item collection</summary>
        /// <param name="position">The date for which to retrieve logs, formatted as MM-dd-yyyy.</param>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.OriginErrors.Item.Item.WithDateTimeItemRequestBuilder"/></returns>
        public global::Soenneker.Bunny.OpenApiClient.OriginErrors.Item.Item.WithDateTimeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("dateTime", position);
                return new global::Soenneker.Bunny.OpenApiClient.OriginErrors.Item.Item.WithDateTimeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.OriginErrors.Item.WithPullZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPullZoneItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/origin-errors/{pullZoneId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.OriginErrors.Item.WithPullZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPullZoneItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/origin-errors/{pullZoneId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
