// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Response containing comprehensive access list information for a Shield Zone, including both managed and custom lists.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessListsDetailsResponse : IParsable
    {
        /// <summary>Total number of entries across all custom access lists for this Shield Zone.</summary>
        public int? CustomEntryCount { get; set; }
        /// <summary>Maximum number of entries allowed across all custom access lists based on the Shield plan.</summary>
        public int? CustomEntryLimit { get; set; }
        /// <summary>Current number of custom access lists for this Shield Zone.</summary>
        public int? CustomListCount { get; set; }
        /// <summary>Maximum number of custom access lists allowed based on the Shield plan.</summary>
        public int? CustomListLimit { get; set; }
        /// <summary>List of custom access lists created and maintained by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>? CustomLists { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails> CustomLists { get; set; }
#endif
        /// <summary>Generic response object containing status information for API operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse? Error { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse Error { get; set; }
#endif
        /// <summary>List of curated threat lists maintained by Bunny Shield with automatic updates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>? ManagedLists { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails> ManagedLists { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.AccessListsDetailsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.AccessListsDetailsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.AccessListsDetailsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customEntryCount", n => { CustomEntryCount = n.GetIntValue(); } },
                { "customEntryLimit", n => { CustomEntryLimit = n.GetIntValue(); } },
                { "customListCount", n => { CustomListCount = n.GetIntValue(); } },
                { "customListLimit", n => { CustomListLimit = n.GetIntValue(); } },
                { "customLists", n => { CustomLists = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>(global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "error", n => { Error = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse>(global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse.CreateFromDiscriminatorValue); } },
                { "managedLists", n => { ManagedLists = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>(global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("customEntryCount", CustomEntryCount);
            writer.WriteIntValue("customEntryLimit", CustomEntryLimit);
            writer.WriteIntValue("customListCount", CustomListCount);
            writer.WriteIntValue("customListLimit", CustomListLimit);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>("customLists", CustomLists);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse>("error", Error);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.AccessListDetails>("managedLists", ManagedLists);
        }
    }
}
#pragma warning restore CS0618
