// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// &quot;The full API Guardian state for a shield zone: global configuration and all endpoints.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiGuardianConfigurationResponse : IParsable
    {
        /// <summary>Global API Guardian configuration for a shield zone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails? Configuration { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails Configuration { get; set; }
#endif
        /// <summary>All endpoints discovered from the uploaded OpenAPI specification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianEndpointDetails>? Endpoints { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianEndpointDetails> Endpoints { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configuration", n => { Configuration = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails>(global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails.CreateFromDiscriminatorValue); } },
                { "endpoints", n => { Endpoints = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianEndpointDetails>(global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianEndpointDetails.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails>("configuration", Configuration);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianEndpointDetails>("endpoints", Endpoints);
        }
    }
}
#pragma warning restore CS0618
