// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Global API Guardian configuration for a shield zone.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiGuardianConfigurationDetails : IParsable
    {
        /// <summary>0 = Block1 = Log2 = Ignore</summary>
        public int? BodyLimitAction { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>0 = Log1 = Block</summary>
        public int? ExecutionMode { get; set; }
        /// <summary>Whether API Guardian is enabled for this shield zone. When disabled, no requests are inspected.</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>Plan limit: maximum number of endpoints that can be defined in the specification.</summary>
        public int? MaxEndpoints { get; set; }
        /// <summary>Plan limit: maximum number of properties a single schema object may declare.</summary>
        public int? MaxFieldsPerType { get; set; }
        /// <summary>Plan limit: maximum depth of nested `$ref`, `items`, and `properties` chains.</summary>
        public int? MaxNestingDepth { get; set; }
        /// <summary>Plan limit: combined character length of all `pattern` regex strings in the specification.</summary>
        public int? MaxTotalRegexLength { get; set; }
        /// <summary>Plan limit: combined node count across all `components/schemas` entries.</summary>
        public int? MaxTotalSchemaNodes { get; set; }
        /// <summary>The shieldZoneId property</summary>
        public int? ShieldZoneId { get; set; }
        /// <summary>The `info.title` field from the uploaded OpenAPI specification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>0 = Block1 = Log2 = Ignore</summary>
        public int? UnmatchedPathAction { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The `info.version` field from the uploaded OpenAPI specification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.ApiGuardianConfigurationDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bodyLimitAction", n => { BodyLimitAction = n.GetIntValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "executionMode", n => { ExecutionMode = n.GetIntValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "maxEndpoints", n => { MaxEndpoints = n.GetIntValue(); } },
                { "maxFieldsPerType", n => { MaxFieldsPerType = n.GetIntValue(); } },
                { "maxNestingDepth", n => { MaxNestingDepth = n.GetIntValue(); } },
                { "maxTotalRegexLength", n => { MaxTotalRegexLength = n.GetIntValue(); } },
                { "maxTotalSchemaNodes", n => { MaxTotalSchemaNodes = n.GetIntValue(); } },
                { "shieldZoneId", n => { ShieldZoneId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "unmatchedPathAction", n => { UnmatchedPathAction = n.GetIntValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("bodyLimitAction", BodyLimitAction);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteIntValue("executionMode", ExecutionMode);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteIntValue("maxEndpoints", MaxEndpoints);
            writer.WriteIntValue("maxFieldsPerType", MaxFieldsPerType);
            writer.WriteIntValue("maxNestingDepth", MaxNestingDepth);
            writer.WriteIntValue("maxTotalRegexLength", MaxTotalRegexLength);
            writer.WriteIntValue("maxTotalSchemaNodes", MaxTotalSchemaNodes);
            writer.WriteIntValue("shieldZoneId", ShieldZoneId);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("unmatchedPathAction", UnmatchedPathAction);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
