// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Application model
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Application : IParsable
    {
        /// <summary>The autoScaling property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.AutoscalingSettings? AutoScaling { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.AutoscalingSettings AutoScaling { get; set; }
#endif
        /// <summary>The containerInstances property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ContainerInstance>? ContainerInstances { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ContainerInstance> ContainerInstances { get; set; }
#endif
        /// <summary>The containerTemplates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ContainerTemplate>? ContainerTemplates { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.ContainerTemplate> ContainerTemplates { get; set; }
#endif
        /// <summary>Display endpoint model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.DisplayEndpoint? DisplayEndpoint { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.DisplayEndpoint DisplayEndpoint { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The networkSettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.NetworkLimits? NetworkSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.NetworkLimits NetworkSettings { get; set; }
#endif
        /// <summary>Region settings model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.RegionSettings? RegionSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.RegionSettings RegionSettings { get; set; }
#endif
        /// <summary>The repositorySettings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.RepositorySettings? RepositorySettings { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.RepositorySettings RepositorySettings { get; set; }
#endif
        /// <summary>The runtimeType property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Models.ApplicationRuntimeType? RuntimeType { get; set; }
        /// <summary>The status property</summary>
        public global::Soenneker.Bunny.OpenApiClient.Models.ApplicationStatus? Status { get; set; }
        /// <summary>The volumes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.VolumeTemplate>? Volumes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.VolumeTemplate> Volumes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.Application"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.Application CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.Application();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "autoScaling", n => { AutoScaling = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.AutoscalingSettings>(global::Soenneker.Bunny.OpenApiClient.Models.AutoscalingSettings.CreateFromDiscriminatorValue); } },
                { "containerInstances", n => { ContainerInstances = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ContainerInstance>(global::Soenneker.Bunny.OpenApiClient.Models.ContainerInstance.CreateFromDiscriminatorValue)?.AsList(); } },
                { "containerTemplates", n => { ContainerTemplates = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ContainerTemplate>(global::Soenneker.Bunny.OpenApiClient.Models.ContainerTemplate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "displayEndpoint", n => { DisplayEndpoint = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.DisplayEndpoint>(global::Soenneker.Bunny.OpenApiClient.Models.DisplayEndpoint.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "networkSettings", n => { NetworkSettings = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.NetworkLimits>(global::Soenneker.Bunny.OpenApiClient.Models.NetworkLimits.CreateFromDiscriminatorValue); } },
                { "regionSettings", n => { RegionSettings = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.RegionSettings>(global::Soenneker.Bunny.OpenApiClient.Models.RegionSettings.CreateFromDiscriminatorValue); } },
                { "repositorySettings", n => { RepositorySettings = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.RepositorySettings>(global::Soenneker.Bunny.OpenApiClient.Models.RepositorySettings.CreateFromDiscriminatorValue); } },
                { "runtimeType", n => { RuntimeType = n.GetEnumValue<global::Soenneker.Bunny.OpenApiClient.Models.ApplicationRuntimeType>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Bunny.OpenApiClient.Models.ApplicationStatus>(); } },
                { "volumes", n => { Volumes = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.VolumeTemplate>(global::Soenneker.Bunny.OpenApiClient.Models.VolumeTemplate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.AutoscalingSettings>("autoScaling", AutoScaling);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ContainerInstance>("containerInstances", ContainerInstances);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.ContainerTemplate>("containerTemplates", ContainerTemplates);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.DisplayEndpoint>("displayEndpoint", DisplayEndpoint);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.NetworkLimits>("networkSettings", NetworkSettings);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.RegionSettings>("regionSettings", RegionSettings);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.RepositorySettings>("repositorySettings", RepositorySettings);
            writer.WriteEnumValue<global::Soenneker.Bunny.OpenApiClient.Models.ApplicationRuntimeType>("runtimeType", RuntimeType);
            writer.WriteEnumValue<global::Soenneker.Bunny.OpenApiClient.Models.ApplicationStatus>("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.VolumeTemplate>("volumes", Volumes);
        }
    }
}
#pragma warning restore CS0618
