// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingAffiliateDetailsModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The amount of affiliate credits on the account</summary>
        public decimal? AffiliateBalance { get; set; }
        /// <summary>The constructed affiliate click history chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateClicksChart? AffiliateClicksChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateClicksChart AffiliateClicksChart { get; set; }
#endif
        /// <summary>The constructed affiliate conversion history chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateConversionsChart? AffiliateConversionsChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateConversionsChart AffiliateConversionsChart { get; set; }
#endif
        /// <summary>The constructed affiliate signup history chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateSignupsChart? AffiliateSignupsChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateSignupsChart AffiliateSignupsChart { get; set; }
#endif
        /// <summary>The affiliate URL for the currently authenticated user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AffiliateUrl { get; set; }
#nullable restore
#else
        public string AffiliateUrl { get; set; }
#endif
        /// <summary>The bonus percentage given when claiming affiliate balance as bunny credits</summary>
        public decimal? ClaimBonusPercentage { get; set; }
        /// <summary>The minimum amount required to request affiliate credits external payout</summary>
        public decimal? MinimumPayoutAmount { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AffiliateBalance", n => { AffiliateBalance = n.GetDecimalValue(); } },
                { "AffiliateClicksChart", n => { AffiliateClicksChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateClicksChart>(global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateClicksChart.CreateFromDiscriminatorValue); } },
                { "AffiliateConversionsChart", n => { AffiliateConversionsChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateConversionsChart>(global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateConversionsChart.CreateFromDiscriminatorValue); } },
                { "AffiliateSignupsChart", n => { AffiliateSignupsChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateSignupsChart>(global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateSignupsChart.CreateFromDiscriminatorValue); } },
                { "AffiliateUrl", n => { AffiliateUrl = n.GetStringValue(); } },
                { "ClaimBonusPercentage", n => { ClaimBonusPercentage = n.GetDecimalValue(); } },
                { "MinimumPayoutAmount", n => { MinimumPayoutAmount = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("AffiliateBalance", AffiliateBalance);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateClicksChart>("AffiliateClicksChart", AffiliateClicksChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateConversionsChart>("AffiliateConversionsChart", AffiliateConversionsChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.BillingAffiliateDetailsModelAffiliateSignupsChart>("AffiliateSignupsChart", AffiliateSignupsChart);
            writer.WriteStringValue("AffiliateUrl", AffiliateUrl);
            writer.WriteDecimalValue("ClaimBonusPercentage", ClaimBonusPercentage);
            writer.WriteDecimalValue("MinimumPayoutAmount", MinimumPayoutAmount);
        }
    }
}
#pragma warning restore CS0618
