// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// The monthly charges and usage for AI Gateway input tokens
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BillingModelMonthlyAiGatewayInputTokens : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Measuring Unit for TotalUnits (e.g. Rows, GB, Seconds, Bytes, Block-seconds)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MeasuringUnit { get; set; }
#nullable restore
#else
        public string MeasuringUnit { get; set; }
#endif
        /// <summary>The billed quantity for the related product</summary>
        public long? TotalUnits { get; set; }
        /// <summary>The usage based charge in USD</summary>
        public decimal? Usage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Models.BillingModelMonthlyAiGatewayInputTokens"/> and sets the default values.
        /// </summary>
        public BillingModelMonthlyAiGatewayInputTokens()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.BillingModelMonthlyAiGatewayInputTokens"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.BillingModelMonthlyAiGatewayInputTokens CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.BillingModelMonthlyAiGatewayInputTokens();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "MeasuringUnit", n => { MeasuringUnit = n.GetStringValue(); } },
                { "TotalUnits", n => { TotalUnits = n.GetLongValue(); } },
                { "Usage", n => { Usage = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("MeasuringUnit", MeasuringUnit);
            writer.WriteLongValue("TotalUnits", TotalUnits);
            writer.WriteDecimalValue("Usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
