// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CollectionModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The unique ID of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; set; }
#nullable restore
#else
        public string Guid { get; set; }
#endif
        /// <summary>The number of live streams in the collection. On-demand videos are not included in this count.</summary>
        public long? LiveStreamCount { get; set; }
        /// <summary>The name of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The URLs of preview images of videos in the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PreviewImageUrls { get; set; }
#nullable restore
#else
        public List<string> PreviewImageUrls { get; set; }
#endif
        /// <summary>Comma-separated list of video GUIDs used as preview thumbnails for the collection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewVideoIds { get; set; }
#nullable restore
#else
        public string PreviewVideoIds { get; set; }
#endif
        /// <summary>The total storage size of all videos in the collection, in bytes.</summary>
        public long? TotalSize { get; set; }
        /// <summary>The number of on-demand videos in the collection. Live streams in the collection are not included in this count.</summary>
        public long? VideoCount { get; set; }
        /// <summary>The video library ID that contains the collection</summary>
        public long? VideoLibraryId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.CollectionModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.CollectionModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.CollectionModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "liveStreamCount", n => { LiveStreamCount = n.GetLongValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "previewImageUrls", n => { PreviewImageUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "previewVideoIds", n => { PreviewVideoIds = n.GetStringValue(); } },
                { "totalSize", n => { TotalSize = n.GetLongValue(); } },
                { "videoCount", n => { VideoCount = n.GetLongValue(); } },
                { "videoLibraryId", n => { VideoLibraryId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("guid", Guid);
            writer.WriteLongValue("liveStreamCount", LiveStreamCount);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfPrimitiveValues<string>("previewImageUrls", PreviewImageUrls);
            writer.WriteStringValue("previewVideoIds", PreviewVideoIds);
            writer.WriteLongValue("totalSize", TotalSize);
            writer.WriteLongValue("videoCount", VideoCount);
            writer.WriteLongValue("videoLibraryId", VideoLibraryId);
        }
    }
}
#pragma warning restore CS0618
