// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContainerProbe : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The failureThreshold property</summary>
        public int? FailureThreshold { get; set; }
        /// <summary>The grpc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.GrpcProbe? Grpc { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.GrpcProbe Grpc { get; set; }
#endif
        /// <summary>The httpGet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.HttpGetProbe? HttpGet { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.HttpGetProbe HttpGet { get; set; }
#endif
        /// <summary>The initialDelaySeconds property</summary>
        public int? InitialDelaySeconds { get; set; }
        /// <summary>The periodSeconds property</summary>
        public int? PeriodSeconds { get; set; }
        /// <summary>The successThreshold property</summary>
        public int? SuccessThreshold { get; set; }
        /// <summary>The tcpSocket property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.TcpSocketProbe? TcpSocket { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.TcpSocketProbe TcpSocket { get; set; }
#endif
        /// <summary>The timeoutSeconds property</summary>
        public int? TimeoutSeconds { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.ContainerProbe"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.ContainerProbe CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.ContainerProbe();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "failureThreshold", n => { FailureThreshold = n.GetIntValue(); } },
                { "grpc", n => { Grpc = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GrpcProbe>(global::Soenneker.Bunny.OpenApiClient.Models.GrpcProbe.CreateFromDiscriminatorValue); } },
                { "httpGet", n => { HttpGet = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.HttpGetProbe>(global::Soenneker.Bunny.OpenApiClient.Models.HttpGetProbe.CreateFromDiscriminatorValue); } },
                { "initialDelaySeconds", n => { InitialDelaySeconds = n.GetIntValue(); } },
                { "periodSeconds", n => { PeriodSeconds = n.GetIntValue(); } },
                { "successThreshold", n => { SuccessThreshold = n.GetIntValue(); } },
                { "tcpSocket", n => { TcpSocket = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.TcpSocketProbe>(global::Soenneker.Bunny.OpenApiClient.Models.TcpSocketProbe.CreateFromDiscriminatorValue); } },
                { "timeoutSeconds", n => { TimeoutSeconds = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("failureThreshold", FailureThreshold);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GrpcProbe>("grpc", Grpc);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.HttpGetProbe>("httpGet", HttpGet);
            writer.WriteIntValue("initialDelaySeconds", InitialDelaySeconds);
            writer.WriteIntValue("periodSeconds", PeriodSeconds);
            writer.WriteIntValue("successThreshold", SuccessThreshold);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.TcpSocketProbe>("tcpSocket", TcpSocket);
            writer.WriteIntValue("timeoutSeconds", TimeoutSeconds);
        }
    }
}
#pragma warning restore CS0618
