// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ContainerEntryPoint : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The arguments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arguments { get; set; }
#nullable restore
#else
        public string Arguments { get; set; }
#endif
        /// <summary>The argumentsArray property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ArgumentsArray { get; set; }
#nullable restore
#else
        public List<string> ArgumentsArray { get; set; }
#endif
        /// <summary>The command property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Command { get; set; }
#nullable restore
#else
        public string Command { get; set; }
#endif
        /// <summary>The commandArray property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CommandArray { get; set; }
#nullable restore
#else
        public List<string> CommandArray { get; set; }
#endif
        /// <summary>The workingDirectory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkingDirectory { get; set; }
#nullable restore
#else
        public string WorkingDirectory { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.ContainerEntryPoint"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.ContainerEntryPoint CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.ContainerEntryPoint();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "arguments", n => { Arguments = n.GetStringValue(); } },
                { "argumentsArray", n => { ArgumentsArray = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "command", n => { Command = n.GetStringValue(); } },
                { "commandArray", n => { CommandArray = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "workingDirectory", n => { WorkingDirectory = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("arguments", Arguments);
            writer.WriteCollectionOfPrimitiveValues<string>("argumentsArray", ArgumentsArray);
            writer.WriteStringValue("command", Command);
            writer.WriteCollectionOfPrimitiveValues<string>("commandArray", CommandArray);
            writer.WriteStringValue("workingDirectory", WorkingDirectory);
        }
    }
}
#pragma warning restore CS0618
