// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateCustomWafRuleModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>1 = Block2 = Log3 = Challenge4 = Allow5 = Bypass</summary>
        public int? ActionType { get; set; }
        /// <summary>The chainedRuleConditions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.WafChainedRuleConditionItem>? ChainedRuleConditions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.WafChainedRuleConditionItem> ChainedRuleConditions { get; set; }
#endif
        /// <summary>0 = BEGINSWITH1 = ENDSWITH2 = CONTAINS3 = CONTAINSWORD4 = STRMATCH5 = EQ6 = GE7 = GT8 = LE9 = LT12 = WITHIN14 = RX15 = STREQ17 = DETECTSQLI18 = DETECTXSS</summary>
        public int? OperatorType { get; set; }
        /// <summary>0 = NOTICE1 = WARNING2 = CRITICAL</summary>
        public int? SeverityType { get; set; }
        /// <summary>The transformationTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? TransformationTypes { get; set; }
#nullable restore
#else
        public List<int?> TransformationTypes { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>The variableTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModelVariableTypes? VariableTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModelVariableTypes VariableTypes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actionType", n => { ActionType = n.GetIntValue(); } },
                { "chainedRuleConditions", n => { ChainedRuleConditions = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.WafChainedRuleConditionItem>(global::Soenneker.Bunny.OpenApiClient.Models.WafChainedRuleConditionItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "operatorType", n => { OperatorType = n.GetIntValue(); } },
                { "severityType", n => { SeverityType = n.GetIntValue(); } },
                { "transformationTypes", n => { TransformationTypes = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "variableTypes", n => { VariableTypes = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModelVariableTypes>(global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModelVariableTypes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("actionType", ActionType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.WafChainedRuleConditionItem>("chainedRuleConditions", ChainedRuleConditions);
            writer.WriteIntValue("operatorType", OperatorType);
            writer.WriteIntValue("severityType", SeverityType);
            writer.WriteCollectionOfPrimitiveValues<int?>("transformationTypes", TransformationTypes);
            writer.WriteStringValue("value", Value);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.CreateCustomWafRuleModelVariableTypes>("variableTypes", VariableTypes);
        }
    }
}
#pragma warning restore CS0618
