// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DnsZoneDiscoveredRecordModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The IsProxied property</summary>
        public bool? IsProxied { get; set; }
        /// <summary>Record name relative to the zone. &apos;@&apos; represents apex.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The Port property</summary>
        public int? Port { get; set; }
        /// <summary>The Priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The Ttl property</summary>
        public int? Ttl { get; set; }
        /// <summary>The Type property</summary>
        public int? Type { get; set; }
        /// <summary>The Value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>The Weight property</summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneDiscoveredRecordModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneDiscoveredRecordModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneDiscoveredRecordModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "IsProxied", n => { IsProxied = n.GetBoolValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "Port", n => { Port = n.GetIntValue(); } },
                { "Priority", n => { Priority = n.GetIntValue(); } },
                { "Ttl", n => { Ttl = n.GetIntValue(); } },
                { "Type", n => { Type = n.GetIntValue(); } },
                { "Value", n => { Value = n.GetStringValue(); } },
                { "Weight", n => { Weight = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("IsProxied", IsProxied);
            writer.WriteStringValue("Name", Name);
            writer.WriteIntValue("Port", Port);
            writer.WriteIntValue("Priority", Priority);
            writer.WriteIntValue("Ttl", Ttl);
            writer.WriteIntValue("Type", Type);
            writer.WriteStringValue("Value", Value);
            writer.WriteIntValue("Weight", Weight);
        }
    }
}
#pragma warning restore CS0618
