// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DnsZoneImportResultModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The RecordsFailed property</summary>
        public int? RecordsFailed { get; set; }
        /// <summary>The RecordsSkipped property</summary>
        public int? RecordsSkipped { get; set; }
        /// <summary>The RecordsSuccessful property</summary>
        public int? RecordsSuccessful { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneImportResultModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneImportResultModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.DnsZoneImportResultModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "RecordsFailed", n => { RecordsFailed = n.GetIntValue(); } },
                { "RecordsSkipped", n => { RecordsSkipped = n.GetIntValue(); } },
                { "RecordsSuccessful", n => { RecordsSuccessful = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("RecordsFailed", RecordsFailed);
            writer.WriteIntValue("RecordsSkipped", RecordsSkipped);
            writer.WriteIntValue("RecordsSuccessful", RecordsSuccessful);
        }
    }
}
#pragma warning restore CS0618
