// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EdgeScriptModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The CurrentReleaseId property</summary>
        public long? CurrentReleaseId { get; set; }
        /// <summary>The DefaultHostname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultHostname { get; set; }
#nullable restore
#else
        public string DefaultHostname { get; set; }
#endif
        /// <summary>The Deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The DeploymentKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentKey { get; set; }
#nullable restore
#else
        public string DeploymentKey { get; set; }
#endif
        /// <summary>The EdgeScriptVariables property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptVariableModel>? EdgeScriptVariables { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptVariableModel> EdgeScriptVariables { get; set; }
#endif
        /// <summary>The Id property</summary>
        public long? Id { get; set; }
        /// <summary>The Integration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModelIntegration? Integration { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModelIntegration Integration { get; set; }
#endif
        /// <summary>The IntegrationId property</summary>
        public long? IntegrationId { get; set; }
        /// <summary>The LastModified property</summary>
        public DateTimeOffset? LastModified { get; set; }
        /// <summary>The LinkedPullZones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.LinkedPullZone>? LinkedPullZones { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.LinkedPullZone> LinkedPullZones { get; set; }
#endif
        /// <summary>The MonthlyCost property</summary>
        public decimal? MonthlyCost { get; set; }
        /// <summary>The MonthlyCpuTime property</summary>
        public long? MonthlyCpuTime { get; set; }
        /// <summary>The MonthlyRequestCount property</summary>
        public long? MonthlyRequestCount { get; set; }
        /// <summary>The Name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The RepositoryId property</summary>
        public long? RepositoryId { get; set; }
        /// <summary>0 = DNS1 = CDN2 = Middleware</summary>
        public int? ScriptType { get; set; }
        /// <summary>The SystemHostname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemHostname { get; set; }
#nullable restore
#else
        public string SystemHostname { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CurrentReleaseId", n => { CurrentReleaseId = n.GetLongValue(); } },
                { "DefaultHostname", n => { DefaultHostname = n.GetStringValue(); } },
                { "Deleted", n => { Deleted = n.GetBoolValue(); } },
                { "DeploymentKey", n => { DeploymentKey = n.GetStringValue(); } },
                { "EdgeScriptVariables", n => { EdgeScriptVariables = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptVariableModel>(global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptVariableModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "Id", n => { Id = n.GetLongValue(); } },
                { "Integration", n => { Integration = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModelIntegration>(global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModelIntegration.CreateFromDiscriminatorValue); } },
                { "IntegrationId", n => { IntegrationId = n.GetLongValue(); } },
                { "LastModified", n => { LastModified = n.GetDateTimeOffsetValue(); } },
                { "LinkedPullZones", n => { LinkedPullZones = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.LinkedPullZone>(global::Soenneker.Bunny.OpenApiClient.Models.LinkedPullZone.CreateFromDiscriminatorValue)?.AsList(); } },
                { "MonthlyCost", n => { MonthlyCost = n.GetDecimalValue(); } },
                { "MonthlyCpuTime", n => { MonthlyCpuTime = n.GetLongValue(); } },
                { "MonthlyRequestCount", n => { MonthlyRequestCount = n.GetLongValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "RepositoryId", n => { RepositoryId = n.GetLongValue(); } },
                { "ScriptType", n => { ScriptType = n.GetIntValue(); } },
                { "SystemHostname", n => { SystemHostname = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("CurrentReleaseId", CurrentReleaseId);
            writer.WriteStringValue("DefaultHostname", DefaultHostname);
            writer.WriteBoolValue("Deleted", Deleted);
            writer.WriteStringValue("DeploymentKey", DeploymentKey);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptVariableModel>("EdgeScriptVariables", EdgeScriptVariables);
            writer.WriteLongValue("Id", Id);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EdgeScriptModelIntegration>("Integration", Integration);
            writer.WriteLongValue("IntegrationId", IntegrationId);
            writer.WriteDateTimeOffsetValue("LastModified", LastModified);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.LinkedPullZone>("LinkedPullZones", LinkedPullZones);
            writer.WriteDecimalValue("MonthlyCost", MonthlyCost);
            writer.WriteLongValue("MonthlyCpuTime", MonthlyCpuTime);
            writer.WriteLongValue("MonthlyRequestCount", MonthlyRequestCount);
            writer.WriteStringValue("Name", Name);
            writer.WriteLongValue("RepositoryId", RepositoryId);
            writer.WriteIntValue("ScriptType", ScriptType);
            writer.WriteStringValue("SystemHostname", SystemHostname);
        }
    }
}
#pragma warning restore CS0618
