// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Request body for exporting a Shield Zone&apos;s full filtered Event Logs set as CSV.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventLogsExportRequest : IParsable
    {
        /// <summary>Optional filters, combined with AND. Repeated values within one filter combine with OR.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.EventLogsFilter>? Filters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.EventLogsFilter> Filters { get; set; }
#endif
        /// <summary>Window start as Unix time in milliseconds (UTC). Required.</summary>
        public long? From { get; set; }
        /// <summary>Optional free-text search across IP, ruleId, URL, User-Agent and rule name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>Window end as Unix time in milliseconds (UTC). Required; must be after BunnyNet.Shield.Api.Entities.Waf.WafLogging.EventLogsExportRequest.from and within the last 72 hours.</summary>
        public long? To { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.EventLogsExportRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.EventLogsExportRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.EventLogsExportRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.EventLogsFilter>(global::Soenneker.Bunny.OpenApiClient.Models.EventLogsFilter.CreateFromDiscriminatorValue)?.AsList(); } },
                { "from", n => { From = n.GetLongValue(); } },
                { "query", n => { Query = n.GetStringValue(); } },
                { "to", n => { To = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.EventLogsFilter>("filters", Filters);
            writer.WriteLongValue("from", From);
            writer.WriteStringValue("query", Query);
            writer.WriteLongValue("to", To);
        }
    }
}
#pragma warning restore CS0618
