// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// An aggregated group of events (returned when the search request specifies groupBy).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventGroup : IParsable
    {
        /// <summary>&quot;Context aggregates for the group: country, asn, per-action counts (blocked/challenged/logged),and features/ruleIds touched. Counts are numbers; features/ruleIds are comma-joined strings.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.EventGroupContext? Context { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.EventGroupContext Context { get; set; }
#endif
        /// <summary>Number of events in the group.</summary>
        public long? Count { get; set; }
        /// <summary>Earliest event time in the group (Unix time in milliseconds, UTC).</summary>
        public long? FirstSeen { get; set; }
        /// <summary>&quot;The group key: each requested groupBy dimension mapped to its value.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.EventGroupKey? Key { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.EventGroupKey Key { get; set; }
#endif
        /// <summary>Most recent event time in the group (Unix time in milliseconds, UTC).</summary>
        public long? LastSeen { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.EventGroup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.EventGroup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.EventGroup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "context", n => { Context = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EventGroupContext>(global::Soenneker.Bunny.OpenApiClient.Models.EventGroupContext.CreateFromDiscriminatorValue); } },
                { "count", n => { Count = n.GetLongValue(); } },
                { "firstSeen", n => { FirstSeen = n.GetLongValue(); } },
                { "key", n => { Key = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EventGroupKey>(global::Soenneker.Bunny.OpenApiClient.Models.EventGroupKey.CreateFromDiscriminatorValue); } },
                { "lastSeen", n => { LastSeen = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EventGroupContext>("context", Context);
            writer.WriteLongValue("count", Count);
            writer.WriteLongValue("firstSeen", FirstSeen);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.EventGroupKey>("key", Key);
            writer.WriteLongValue("lastSeen", LastSeen);
        }
    }
}
#pragma warning restore CS0618
