// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssueCodes : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper? IssueCodesOneOf10Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper IssueCodesOneOf10Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper? IssueCodesOneOf11Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper IssueCodesOneOf11Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper? IssueCodesOneOf12Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper IssueCodesOneOf12Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper? IssueCodesOneOf1Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper IssueCodesOneOf1Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper? IssueCodesOneOf2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper IssueCodesOneOf2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper? IssueCodesOneOf3Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper IssueCodesOneOf3Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper? IssueCodesOneOf4Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper IssueCodesOneOf4Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper? IssueCodesOneOf5Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper IssueCodesOneOf5Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper? IssueCodesOneOf6Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper IssueCodesOneOf6Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper? IssueCodesOneOf7Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper IssueCodesOneOf7Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper? IssueCodesOneOf8Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper IssueCodesOneOf8Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper? IssueCodesOneOf9Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper IssueCodesOneOf9Wrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.IssueCodes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.IssueCodes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodes();
            if("IssueCodesOneOf10Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf10Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper();
            }
            else if("IssueCodesOneOf11Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf11Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper();
            }
            else if("IssueCodesOneOf12Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf12Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper();
            }
            else if("IssueCodesOneOf1Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf1Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper();
            }
            else if("IssueCodesOneOf2Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf2Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper();
            }
            else if("IssueCodesOneOf3Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf3Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper();
            }
            else if("IssueCodesOneOf4Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf4Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper();
            }
            else if("IssueCodesOneOf5Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf5Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper();
            }
            else if("IssueCodesOneOf6Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf6Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper();
            }
            else if("IssueCodesOneOf7Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf7Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper();
            }
            else if("IssueCodesOneOf8Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf8Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper();
            }
            else if("IssueCodesOneOf9Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IssueCodesOneOf9Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(IssueCodesOneOf10Wrapper != null)
            {
                return IssueCodesOneOf10Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf11Wrapper != null)
            {
                return IssueCodesOneOf11Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf12Wrapper != null)
            {
                return IssueCodesOneOf12Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf1Wrapper != null)
            {
                return IssueCodesOneOf1Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf2Wrapper != null)
            {
                return IssueCodesOneOf2Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf3Wrapper != null)
            {
                return IssueCodesOneOf3Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf4Wrapper != null)
            {
                return IssueCodesOneOf4Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf5Wrapper != null)
            {
                return IssueCodesOneOf5Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf6Wrapper != null)
            {
                return IssueCodesOneOf6Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf7Wrapper != null)
            {
                return IssueCodesOneOf7Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf8Wrapper != null)
            {
                return IssueCodesOneOf8Wrapper.GetFieldDeserializers();
            }
            else if(IssueCodesOneOf9Wrapper != null)
            {
                return IssueCodesOneOf9Wrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IssueCodesOneOf10Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf10Wrapper>(null, IssueCodesOneOf10Wrapper);
            }
            else if(IssueCodesOneOf11Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf11Wrapper>(null, IssueCodesOneOf11Wrapper);
            }
            else if(IssueCodesOneOf12Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf12Wrapper>(null, IssueCodesOneOf12Wrapper);
            }
            else if(IssueCodesOneOf1Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf1Wrapper>(null, IssueCodesOneOf1Wrapper);
            }
            else if(IssueCodesOneOf2Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf2Wrapper>(null, IssueCodesOneOf2Wrapper);
            }
            else if(IssueCodesOneOf3Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf3Wrapper>(null, IssueCodesOneOf3Wrapper);
            }
            else if(IssueCodesOneOf4Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf4Wrapper>(null, IssueCodesOneOf4Wrapper);
            }
            else if(IssueCodesOneOf5Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf5Wrapper>(null, IssueCodesOneOf5Wrapper);
            }
            else if(IssueCodesOneOf6Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf6Wrapper>(null, IssueCodesOneOf6Wrapper);
            }
            else if(IssueCodesOneOf7Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf7Wrapper>(null, IssueCodesOneOf7Wrapper);
            }
            else if(IssueCodesOneOf8Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf8Wrapper>(null, IssueCodesOneOf8Wrapper);
            }
            else if(IssueCodesOneOf9Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.IssueCodesOneOf9Wrapper>(null, IssueCodesOneOf9Wrapper);
            }
        }
    }
}
#pragma warning restore CS0618
