// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoadBalancerOriginLatencySeriesModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The OriginId property</summary>
        public long? OriginId { get; set; }
        /// <summary>The OriginName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginName { get; set; }
#nullable restore
#else
        public string OriginName { get; set; }
#endif
        /// <summary>The Percentile property</summary>
        public int? Percentile { get; set; }
        /// <summary>The Values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModelValuesProperty2? Values { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModelValuesProperty2 Values { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModel"/> and sets the default values.
        /// </summary>
        public LoadBalancerOriginLatencySeriesModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "OriginId", n => { OriginId = n.GetLongValue(); } },
                { "OriginName", n => { OriginName = n.GetStringValue(); } },
                { "Percentile", n => { Percentile = n.GetIntValue(); } },
                { "Values", n => { Values = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModelValuesProperty2>(global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModelValuesProperty2.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("OriginId", OriginId);
            writer.WriteStringValue("OriginName", OriginName);
            writer.WriteIntValue("Percentile", Percentile);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginLatencySeriesModelValuesProperty2>("Values", Values);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
