// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoadBalancerPricingTierModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The PricePerMillion property</summary>
        public decimal? PricePerMillion { get; set; }
        /// <summary>The ThresholdFromMillions property</summary>
        public long? ThresholdFromMillions { get; set; }
        /// <summary>The ThresholdToMillions property</summary>
        public long? ThresholdToMillions { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerPricingTierModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerPricingTierModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerPricingTierModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "PricePerMillion", n => { PricePerMillion = n.GetDecimalValue(); } },
                { "ThresholdFromMillions", n => { ThresholdFromMillions = n.GetLongValue(); } },
                { "ThresholdToMillions", n => { ThresholdToMillions = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("PricePerMillion", PricePerMillion);
            writer.WriteLongValue("ThresholdFromMillions", ThresholdFromMillions);
            writer.WriteLongValue("ThresholdToMillions", ThresholdToMillions);
        }
    }
}
#pragma warning restore CS0618
