// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LoadBalancerOriginCreateModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ID of the Edge Script to use as the origin - required when using the EdgeScript origin type</summary>
        public long? EdgeScriptId { get; set; }
        /// <summary>Whether traffic should route to this origin</summary>
        public bool? Enabled { get; set; }
        /// <summary>Magic Containers origin settings - required when using the Magic Containers origin type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelMagicContainersOrigin? MagicContainersOrigin { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelMagicContainersOrigin MagicContainersOrigin { get; set; }
#endif
        /// <summary>The type of origin to connect to</summary>
        public int? OriginType { get; set; }
        /// <summary>Standard origin settings - required when using the Standard origin type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelStandardOrigin? StandardOrigin { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelStandardOrigin StandardOrigin { get; set; }
#endif
        /// <summary>The ID of the Storage Zone to use as the origin - required when using the Storage origin type</summary>
        public long? StorageZoneId { get; set; }
        /// <summary>The weight of the origin used for weighted load balancing</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? Weight { get; set; }
#nullable restore
#else
        public byte[] Weight { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "EdgeScriptId", n => { EdgeScriptId = n.GetLongValue(); } },
                { "Enabled", n => { Enabled = n.GetBoolValue(); } },
                { "MagicContainersOrigin", n => { MagicContainersOrigin = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelMagicContainersOrigin>(global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelMagicContainersOrigin.CreateFromDiscriminatorValue); } },
                { "OriginType", n => { OriginType = n.GetIntValue(); } },
                { "StandardOrigin", n => { StandardOrigin = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelStandardOrigin>(global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelStandardOrigin.CreateFromDiscriminatorValue); } },
                { "StorageZoneId", n => { StorageZoneId = n.GetLongValue(); } },
                { "Weight", n => { Weight = n.GetByteArrayValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("EdgeScriptId", EdgeScriptId);
            writer.WriteBoolValue("Enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelMagicContainersOrigin>("MagicContainersOrigin", MagicContainersOrigin);
            writer.WriteIntValue("OriginType", OriginType);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.LoadBalancerOriginCreateModelStandardOrigin>("StandardOrigin", StandardOrigin);
            writer.WriteLongValue("StorageZoneId", StorageZoneId);
            writer.WriteByteArrayValue("Weight", Weight);
        }
    }
}
#pragma warning restore CS0618
