// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OriginShieldConcurrencyStatisticsModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The constructed chart of origin shield concurrent requests</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelConcurrentRequestsChart? ConcurrentRequestsChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelConcurrentRequestsChart ConcurrentRequestsChart { get; set; }
#endif
        /// <summary>The constructed chart of origin shield requests chart</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelQueuedRequestsChart? QueuedRequestsChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelQueuedRequestsChart QueuedRequestsChart { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ConcurrentRequestsChart", n => { ConcurrentRequestsChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelConcurrentRequestsChart>(global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelConcurrentRequestsChart.CreateFromDiscriminatorValue); } },
                { "QueuedRequestsChart", n => { QueuedRequestsChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelQueuedRequestsChart>(global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelQueuedRequestsChart.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelConcurrentRequestsChart>("ConcurrentRequestsChart", ConcurrentRequestsChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.OriginShieldConcurrencyStatisticsModelQueuedRequestsChart>("QueuedRequestsChart", QueuedRequestsChart);
        }
    }
}
#pragma warning restore CS0618
