// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentRequestModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Amount property</summary>
        public decimal? Amount { get; set; }
        /// <summary>The BankTransferReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankTransferReference { get; set; }
#nullable restore
#else
        public string BankTransferReference { get; set; }
#endif
        /// <summary>The BillingInvoiceDownloadLink property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingInvoiceDownloadLink { get; set; }
#nullable restore
#else
        public string BillingInvoiceDownloadLink { get; set; }
#endif
        /// <summary>The BillingInvoiceId property</summary>
        public long? BillingInvoiceId { get; set; }
        /// <summary>The DateDue property</summary>
        public DateTimeOffset? DateDue { get; set; }
        /// <summary>The DateGenerated property</summary>
        public DateTimeOffset? DateGenerated { get; set; }
        /// <summary>The DatePaid property</summary>
        public DateTimeOffset? DatePaid { get; set; }
        /// <summary>The Description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The Id property</summary>
        public long? Id { get; set; }
        /// <summary>The Paid property</summary>
        public bool? Paid { get; set; }
        /// <summary>The TaxedAmount property</summary>
        public decimal? TaxedAmount { get; set; }
        /// <summary>The TaxRate property</summary>
        public decimal? TaxRate { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.PaymentRequestModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.PaymentRequestModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.PaymentRequestModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Amount", n => { Amount = n.GetDecimalValue(); } },
                { "BankTransferReference", n => { BankTransferReference = n.GetStringValue(); } },
                { "BillingInvoiceDownloadLink", n => { BillingInvoiceDownloadLink = n.GetStringValue(); } },
                { "BillingInvoiceId", n => { BillingInvoiceId = n.GetLongValue(); } },
                { "DateDue", n => { DateDue = n.GetDateTimeOffsetValue(); } },
                { "DateGenerated", n => { DateGenerated = n.GetDateTimeOffsetValue(); } },
                { "DatePaid", n => { DatePaid = n.GetDateTimeOffsetValue(); } },
                { "Description", n => { Description = n.GetStringValue(); } },
                { "Id", n => { Id = n.GetLongValue(); } },
                { "Paid", n => { Paid = n.GetBoolValue(); } },
                { "TaxRate", n => { TaxRate = n.GetDecimalValue(); } },
                { "TaxedAmount", n => { TaxedAmount = n.GetDecimalValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDecimalValue("Amount", Amount);
            writer.WriteStringValue("BankTransferReference", BankTransferReference);
            writer.WriteStringValue("BillingInvoiceDownloadLink", BillingInvoiceDownloadLink);
            writer.WriteLongValue("BillingInvoiceId", BillingInvoiceId);
            writer.WriteDateTimeOffsetValue("DateDue", DateDue);
            writer.WriteDateTimeOffsetValue("DateGenerated", DateGenerated);
            writer.WriteDateTimeOffsetValue("DatePaid", DatePaid);
            writer.WriteStringValue("Description", Description);
            writer.WriteLongValue("Id", Id);
            writer.WriteBoolValue("Paid", Paid);
            writer.WriteDecimalValue("TaxedAmount", TaxedAmount);
            writer.WriteDecimalValue("TaxRate", TaxRate);
        }
    }
}
#pragma warning restore CS0618
