// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PodStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "notScheduled")]
        #pragma warning disable CS1591
        NotScheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "scheduled")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "ready")]
        #pragma warning disable CS1591
        Ready,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleting")]
        #pragma warning disable CS1591
        Deleting,
        #pragma warning restore CS1591
    }
}
