// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PullZoneAddModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Sets the list of extensions that will return the CORS headers</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AccessControlOriginHeaderExtensions { get; set; }
#nullable restore
#else
        public List<string> AccessControlOriginHeaderExtensions { get; set; }
#endif
        /// <summary>Determines if the canonical header should be added by this zone</summary>
        public bool? AddCanonicalHeader { get; set; }
        /// <summary>Determines if the zone should forward the requested host header to the origin</summary>
        public bool? AddHostHeader { get; set; }
        /// <summary>Sets the list of referrer hostnames that are allowed to access the pull zone. Requests containing the header Referer: hostname that is not on the list will be rejected. If empty, all the referrers are allowed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedReferrers { get; set; }
#nullable restore
#else
        public List<string> AllowedReferrers { get; set; }
#endif
        /// <summary>Determines if the AWS signing should be enabled or not</summary>
        public bool? AWSSigningEnabled { get; set; }
        /// <summary>Sets the AWS signing key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AWSSigningKey { get; set; }
#nullable restore
#else
        public string AWSSigningKey { get; set; }
#endif
        /// <summary>Sets the AWS signing region name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AWSSigningRegionName { get; set; }
#nullable restore
#else
        public string AWSSigningRegionName { get; set; }
#endif
        /// <summary>Sets the AWS signing secret key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AWSSigningSecret { get; set; }
#nullable restore
#else
        public string AWSSigningSecret { get; set; }
#endif
        /// <summary>Sets the list of two letter Alpha2 country codes that will be blocked from accessing the zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BlockedCountries { get; set; }
#nullable restore
#else
        public List<string> BlockedCountries { get; set; }
#endif
        /// <summary>Sets the list of IPs that are blocked from accessing the pull zone. Requests coming from the following IPs will be rejected. If empty, all the IPs will be allowed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BlockedIps { get; set; }
#nullable restore
#else
        public List<string> BlockedIps { get; set; }
#endif
        /// <summary>Sets the list of referrer hostnames that are blocked from accessing the pull zone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BlockedReferrers { get; set; }
#nullable restore
#else
        public List<string> BlockedReferrers { get; set; }
#endif
        /// <summary>The BlockNoneReferrer property</summary>
        public bool? BlockNoneReferrer { get; set; }
        /// <summary>Determines if the POST requests to this zone should be rejected.</summary>
        public bool? BlockPostRequests { get; set; }
        /// <summary>Determines if the zone should block requests to the root of the zone.</summary>
        public bool? BlockRootPathAccess { get; set; }
        /// <summary>Sets the list of two letter Alpha2 country codes that will be redirected to the cheapest possible region</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BudgetRedirectedCountries { get; set; }
#nullable restore
#else
        public List<string> BudgetRedirectedCountries { get; set; }
#endif
        /// <summary>The BunnyAiImageBlueprints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.BunnyAiImageBlueprintModel>? BunnyAiImageBlueprints { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.BunnyAiImageBlueprintModel> BunnyAiImageBlueprints { get; set; }
#endif
        /// <summary>Determines the maximum burst requests before an IP is blocked</summary>
        public int? BurstSize { get; set; }
        /// <summary>(Deprecated) Sets the browser cache control override setting for this zone</summary>
        public long? CacheControlBrowserMaxAgeOverride { get; set; }
        /// <summary>Sets the cache control override setting for this zone</summary>
        public long? CacheControlMaxAgeOverride { get; set; }
        /// <summary>Sets the browser cache control override setting for this zone</summary>
        public long? CacheControlPublicMaxAgeOverride { get; set; }
        /// <summary>Determines if the cache error responses should be enabled on the zone</summary>
        public bool? CacheErrorResponses { get; set; }
        /// <summary>Vary Cache by Request Headers (comma delimited)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CacheKeyHeaders { get; set; }
#nullable restore
#else
        public string CacheKeyHeaders { get; set; }
#endif
        /// <summary>Determines the maximum number of connections per IP that will be allowed to connect to this Pull Zone</summary>
        public int? ConnectionLimitPerIPCount { get; set; }
        /// <summary>Contains the list of vary parameters that will be used for vary cache by cookie string.Only alphanumeric characters, dashes and underscores are allowed (values that contain other characters are ignorred). If empty, cookie vary will not be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CookieVaryParameters { get; set; }
#nullable restore
#else
        public List<string> CookieVaryParameters { get; set; }
#endif
        /// <summary>Determines if the Pull Zone should automatically remove cookies from the responses</summary>
        public bool? DisableCookies { get; set; }
        /// <summary>If set to true, the built-in let&apos;s encrypt will be disabled and requests are passed to the origin.</summary>
        public bool? DisableLetsEncrypt { get; set; }
        /// <summary>Determines the origin port of the pull zone.</summary>
        public int? DnsOriginPort { get; set; }
        /// <summary>Determines the origin scheme of the pull zone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DnsOriginScheme { get; set; }
#nullable restore
#else
        public string DnsOriginScheme { get; set; }
#endif
        /// <summary>The execution phase of the edge script</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelEdgeScriptExecutionPhase? EdgeScriptExecutionPhase { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelEdgeScriptExecutionPhase EdgeScriptExecutionPhase { get; set; }
#endif
        /// <summary>The ID of the edge script that will be used as the origin</summary>
        public long? EdgeScriptId { get; set; }
        /// <summary>Determines if CORS headers should be enabled</summary>
        public bool? EnableAccessControlOriginHeader { get; set; }
        /// <summary>If set to true, any hostnames added to this Pull Zone will automatically enable SSL.</summary>
        public bool? EnableAutoSSL { get; set; }
        /// <summary>Determines if the AVIF Vary feature should be enabled.</summary>
        public bool? EnableAvifVary { get; set; }
        /// <summary>The EnableBunnyImageAi property</summary>
        public bool? EnableBunnyImageAi { get; set; }
        /// <summary>Determines if cache slicing (Optimize for video) should be enabled for this zone</summary>
        public bool? EnableCacheSlice { get; set; }
        /// <summary>Determines if the Cookie Vary feature is enabled.</summary>
        public bool? EnableCookieVary { get; set; }
        /// <summary>Determines if the Country Code Vary feature should be enabled.</summary>
        public bool? EnableCountryCodeVary { get; set; }
        /// <summary>Determines if the Country State Code Vary feature should be enabled.</summary>
        public bool? EnableCountryStateCodeVary { get; set; }
        /// <summary>Determines if the delivery from the Africa region should be enabled for this pull zone</summary>
        public bool? EnableGeoZoneAF { get; set; }
        /// <summary>Determines if the delivery from the Asia / Oceania regions should be enabled for this pull zone</summary>
        public bool? EnableGeoZoneASIA { get; set; }
        /// <summary>Determines if the delivery from the Europe region should be enabled for this pull zone</summary>
        public bool? EnableGeoZoneEU { get; set; }
        /// <summary>Determines if the delivery from the South America region should be enabled for this pull zone</summary>
        public bool? EnableGeoZoneSA { get; set; }
        /// <summary>Determines if the delivery from the North America region should be enabled for this pull zone</summary>
        public bool? EnableGeoZoneUS { get; set; }
        /// <summary>Determines if the Hostname Vary feature should be enabled.</summary>
        public bool? EnableHostnameVary { get; set; }
        /// <summary>Determines if the logging should be enabled for this zone</summary>
        public bool? EnableLogging { get; set; }
        /// <summary>Determines if the Mobile Vary feature is enabled.</summary>
        public bool? EnableMobileVary { get; set; }
        /// <summary>Determines if the origin shield should be enabled</summary>
        public bool? EnableOriginShield { get; set; }
        /// <summary>Determines if the query string ordering should be enabled.</summary>
        public bool? EnableQueryStringOrdering { get; set; }
        /// <summary>Determines if request coalescing is currently enabled.</summary>
        public bool? EnableRequestCoalescing { get; set; }
        /// <summary>The EnableSafeHop property</summary>
        public bool? EnableSafeHop { get; set; }
        /// <summary>The EnableSmartCache property</summary>
        public bool? EnableSmartCache { get; set; }
        /// <summary>Determines if the TLS 1 should be enabled on this zone</summary>
        public bool? EnableTLS1 { get; set; }
        /// <summary>Determines if the TLS 1.1 should be enabled on this zone</summary>
        public bool? EnableTLS11 { get; set; }
        /// <summary>Determines if the WebP Vary feature should be enabled.</summary>
        public bool? EnableWebpVary { get; set; }
        /// <summary>Determines if WebSocket connections are allowed for this Pull Zone.</summary>
        public bool? EnableWebSockets { get; set; }
        /// <summary>Contains the custom error page code that will be returned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorPageCustomCode { get; set; }
#nullable restore
#else
        public string ErrorPageCustomCode { get; set; }
#endif
        /// <summary>Determines if custom error page code should be enabled.</summary>
        public bool? ErrorPageEnableCustomCode { get; set; }
        /// <summary>Determines if the statuspage widget should be displayed on the error pages</summary>
        public bool? ErrorPageEnableStatuspageWidget { get; set; }
        /// <summary>The statuspage code that will be used to build the status widget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorPageStatuspageCode { get; set; }
#nullable restore
#else
        public string ErrorPageStatuspageCode { get; set; }
#endif
        /// <summary>Determines if the error pages should be whitelabel or not</summary>
        public bool? ErrorPageWhitelabel { get; set; }
        /// <summary>Determines if the zone should follow redirects return by the oprigin and cache the response</summary>
        public bool? FollowRedirects { get; set; }
        /// <summary>Determines if the Pull Zone should ignore query strings when serving cached objects (Vary by Query String)</summary>
        public bool? IgnoreQueryStrings { get; set; }
        /// <summary>Address-family policy: 0=IPv4Only, 1=DualStack (default, best latency and compatibility), 2=DualStackPreferIPv6, 3=IPv6Only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelIpFamilyPolicy? IpFamilyPolicy { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelIpFamilyPolicy IpFamilyPolicy { get; set; }
#endif
        /// <summary>Determines the amount of traffic transferred before the client is limited</summary>
        public double? LimitRateAfter { get; set; }
        /// <summary>Determines the maximum number of requests per second coming from a single IP before it is blocked.</summary>
        public int? LimitRatePerSecond { get; set; }
        /// <summary>If using a load balancer origin, the ID of the load balancer to use</summary>
        public long? LoadBalancerId { get; set; }
        /// <summary>Sets the log anonymization type for this pull zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogAnonymizationType? LogAnonymizationType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogAnonymizationType LogAnonymizationType { get; set; }
#endif
        /// <summary>The LogFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogFormat? LogFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogFormat LogFormat { get; set; }
#endif
        /// <summary>Sets the log forwarding token for the zone</summary>
        public bool? LogForwardingEnabled { get; set; }
        /// <summary>The LogForwardingFormat property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingFormat? LogForwardingFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingFormat LogForwardingFormat { get; set; }
#endif
        /// <summary>Sets the log forwarding destination hostname for the zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogForwardingHostname { get; set; }
#nullable restore
#else
        public string LogForwardingHostname { get; set; }
#endif
        /// <summary>Sets the log forwarding port for the zone</summary>
        public int? LogForwardingPort { get; set; }
        /// <summary>Sets the log forwarding protocol type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingProtocol? LogForwardingProtocol { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingProtocol LogForwardingProtocol { get; set; }
#endif
        /// <summary>Sets the log forwarding token for the zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogForwardingToken { get; set; }
#nullable restore
#else
        public string LogForwardingToken { get; set; }
#endif
        /// <summary>Determines if the log anonoymization should be enabled</summary>
        public bool? LoggingIPAnonymizationEnabled { get; set; }
        /// <summary>Determines if the logging permanent storage should be enabled</summary>
        public bool? LoggingSaveToStorage { get; set; }
        /// <summary>Sets the Storage Zone id that should contain the logs from this Pull Zone</summary>
        public long? LoggingStorageZoneId { get; set; }
        /// <summary>The MagicContainersAppId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MagicContainersAppId { get; set; }
#nullable restore
#else
        public string MagicContainersAppId { get; set; }
#endif
        /// <summary>The MagicContainersEndpointId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MagicContainersEndpointId { get; set; }
#nullable restore
#else
        public string MagicContainersEndpointId { get; set; }
#endif
        /// <summary>The maximum global simultaneous WebSocket connections allowed for this Pull Zone. Allowed tiers: 500, 1,000, 2,500, 5,000, 10,000, 25,000. If you send a non-tier value, the value is rounded up to the next tier. Values over 25,000 are rejected, please contact sales if required.</summary>
        public int? MaxWebSocketConnections { get; set; }
        /// <summary>The ID of the middleware script</summary>
        public long? MiddlewareScriptId { get; set; }
        /// <summary>Sets the monthly limit of bandwidth in bytes that the pullzone is allowed to use</summary>
        public long? MonthlyBandwidthLimit { get; set; }
        /// <summary>The name of the pull zone.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Determines if the automatic image optimization should be enabled</summary>
        public bool? OptimizerAutomaticOptimizationEnabled { get; set; }
        /// <summary>Determines the list of optimizer classes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneOptimizerClassModel>? OptimizerClasses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneOptimizerClassModel> OptimizerClasses { get; set; }
#endif
        /// <summary>Determines the maximum automatic image size for desktop clients</summary>
        public int? OptimizerDesktopMaxWidth { get; set; }
        /// <summary>Determines if the optimizer should be enabled for this zone</summary>
        public bool? OptimizerEnabled { get; set; }
        /// <summary>Determines the image manipulation should be enabled</summary>
        public bool? OptimizerEnableManipulationEngine { get; set; }
        /// <summary>Determines if Optimizer is allowed to upscale images</summary>
        public bool? OptimizerEnableUpscaling { get; set; }
        /// <summary>Determines if the WebP optimization should be enabled</summary>
        public bool? OptimizerEnableWebP { get; set; }
        /// <summary>Determines if the optimizer classes should be forced</summary>
        public bool? OptimizerForceClasses { get; set; }
        /// <summary>Determines if Markdown automatic generation for AI systems is enabled and which pipeline to use</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerHtmlToMarkdown? OptimizerHtmlToMarkdown { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerHtmlToMarkdown OptimizerHtmlToMarkdown { get; set; }
#endif
        /// <summary>Determines the image quality for desktop clients</summary>
        public int? OptimizerImageQuality { get; set; }
        /// <summary>Determines if the llms.txt file can be generated and served by the Optimizer</summary>
        public bool? OptimizerLlmsTxt { get; set; }
        /// <summary>Determines if the CSS minifcation should be enabled</summary>
        public bool? OptimizerMinifyCSS { get; set; }
        /// <summary>Determines if the JavaScript minifcation should be enabled</summary>
        public bool? OptimizerMinifyJavaScript { get; set; }
        /// <summary>Determines the image quality for mobile clients</summary>
        public int? OptimizerMobileImageQuality { get; set; }
        /// <summary>Determines the maximum automatic image size for mobile clients</summary>
        public int? OptimizerMobileMaxWidth { get; set; }
        /// <summary>Determines if the SEO HTML prerender should be enabled</summary>
        public bool? OptimizerPrerenderHtml { get; set; }
        /// <summary>Determines whether optimizer static html feature enabled</summary>
        public bool? OptimizerStaticHtmlEnabled { get; set; }
        /// <summary>Wordpress cookie which should be bypassed by permacache in edge rule</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptimizerStaticHtmlWordPressBypassCookie { get; set; }
#nullable restore
#else
        public string OptimizerStaticHtmlWordPressBypassCookie { get; set; }
#endif
        /// <summary>Wordpress html path which should be bypassed by permacache in edge rule</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptimizerStaticHtmlWordPressPath { get; set; }
#nullable restore
#else
        public string OptimizerStaticHtmlWordPressPath { get; set; }
#endif
        /// <summary>Determines if the optimizer origin tunnel system should be enabled for this zone</summary>
        public bool? OptimizerTunnelEnabled { get; set; }
        /// <summary>Determines if image watermarking should be enabled</summary>
        public bool? OptimizerWatermarkEnabled { get; set; }
        /// <summary>Sets the minimum image size to which the watermark will be added</summary>
        public int? OptimizerWatermarkMinImageSize { get; set; }
        /// <summary>Sets the offset of the watermark image</summary>
        public double? OptimizerWatermarkOffset { get; set; }
        /// <summary>Sets the position of the watermark image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerWatermarkPosition? OptimizerWatermarkPosition { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerWatermarkPosition OptimizerWatermarkPosition { get; set; }
#endif
        /// <summary>Sets the URL of the watermark image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OptimizerWatermarkUrl { get; set; }
#nullable restore
#else
        public string OptimizerWatermarkUrl { get; set; }
#endif
        /// <summary>The amount of seconds to wait when connecting to the origin. Otherwise the request will fail or retry.</summary>
        public int? OriginConnectTimeout { get; set; }
        /// <summary>Sets the host header that will be sent to the origin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginHostHeader { get; set; }
#nullable restore
#else
        public string OriginHostHeader { get; set; }
#endif
        /// <summary>The amount of seconds to wait when waiting for the origin reply. Otherwise the request will fail or retry.</summary>
        public int? OriginResponseTimeout { get; set; }
        /// <summary>The number of retries to the origin server</summary>
        public int? OriginRetries { get; set; }
        /// <summary>Determines if we should retry the request in case of a 5XX response.</summary>
        public bool? OriginRetry5XXResponses { get; set; }
        /// <summary>Determines if we should retry the request in case of a connection timeout.</summary>
        public bool? OriginRetryConnectionTimeout { get; set; }
        /// <summary>Determines the amount of time that the CDN should wait before retrying an origin request.</summary>
        public int? OriginRetryDelay { get; set; }
        /// <summary>Determines if we should retry the request in case of a response timeout.</summary>
        public bool? OriginRetryResponseTimeout { get; set; }
        /// <summary>Determines if the origin shield concurrency limit is enabled.</summary>
        public bool? OriginShieldEnableConcurrencyLimit { get; set; }
        /// <summary>Determines the number of maximum concurrent requests allowed to the origin.</summary>
        public int? OriginShieldMaxConcurrentRequests { get; set; }
        /// <summary>Determines the max number of origin requests that will remain in the queue</summary>
        public int? OriginShieldMaxQueuedRequests { get; set; }
        /// <summary>Determines the max queue wait time</summary>
        public int? OriginShieldQueueMaxWaitTime { get; set; }
        /// <summary>Determines the zone code where the origin shield should be set up</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginShieldZoneCode { get; set; }
#nullable restore
#else
        public string OriginShieldZoneCode { get; set; }
#endif
        /// <summary>Determine the type of the origin for this Pull Zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOriginType? OriginType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOriginType OriginType { get; set; }
#endif
        /// <summary>Sets the origin URL of the Pull Zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginUrl { get; set; }
#nullable restore
#else
        public string OriginUrl { get; set; }
#endif
        /// <summary>The ID of the storage zone that should be used as the Perma-Cache</summary>
        public long? PermaCacheStorageZoneId { get; set; }
        /// <summary>Determines Perma-Cache behavior</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPermaCacheType? PermaCacheType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPermaCacheType PermaCacheType { get; set; }
#endif
        /// <summary>The custom preloading screen coed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreloadingScreenCode { get; set; }
#nullable restore
#else
        public string PreloadingScreenCode { get; set; }
#endif
        /// <summary>Determines if the custom preloader screen should be enabled</summary>
        public bool? PreloadingScreenCodeEnabled { get; set; }
        /// <summary>The delay in miliseconds after which the preloading screen will be displayed (0 - 10000ms)</summary>
        public int? PreloadingScreenDelay { get; set; }
        /// <summary>Determines if the preloading screen is currently enabled</summary>
        public bool? PreloadingScreenEnabled { get; set; }
        /// <summary>The preloading screen logo URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreloadingScreenLogoUrl { get; set; }
#nullable restore
#else
        public string PreloadingScreenLogoUrl { get; set; }
#endif
        /// <summary>Determines if the preloading screen is shown on the first load from a user.</summary>
        public bool? PreloadingScreenShowOnFirstVisit { get; set; }
        /// <summary>The currently configured preloading screem theme. (0 - Light, 1 - Dark)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPreloadingScreenTheme? PreloadingScreenTheme { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPreloadingScreenTheme PreloadingScreenTheme { get; set; }
#endif
        /// <summary>Contains the list of vary parameters that will be used for vary cache by query string. Only alphanumeric characters, dashes and underscores are allowed (values that contain other characters are ignorred). If empty, all parameters will be used to construct the key.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? QueryStringVaryParameters { get; set; }
#nullable restore
#else
        public List<string> QueryStringVaryParameters { get; set; }
#endif
        /// <summary>Determines the lock time for coalesced requests.</summary>
        public int? RequestCoalescingTimeout { get; set; }
        /// <summary>Determines the maximum number of requests per second that will be allowed to connect to this Pull Zone</summary>
        public int? RequestLimit { get; set; }
        /// <summary>The list of routing filters enabled for this zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RoutingFilters { get; set; }
#nullable restore
#else
        public List<string> RoutingFilters { get; set; }
#endif
        /// <summary>The ShieldDDosProtectionEnabled property</summary>
        public bool? ShieldDDosProtectionEnabled { get; set; }
        /// <summary>The ShieldDDosProtectionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelShieldDDosProtectionType? ShieldDDosProtectionType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelShieldDDosProtectionType ShieldDDosProtectionType { get; set; }
#endif
        /// <summary>A set of comma-separated header names used to identify clients</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StickySessionClientHeaders { get; set; }
#nullable restore
#else
        public string StickySessionClientHeaders { get; set; }
#endif
        /// <summary>Sticky Session Cookie Name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StickySessionCookieName { get; set; }
#nullable restore
#else
        public string StickySessionCookieName { get; set; }
#endif
        /// <summary>Whether to use a Sticky Session mechanism for this pull zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelStickySessionType? StickySessionType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelStickySessionType StickySessionType { get; set; }
#endif
        /// <summary>The ID of the storage zone that will be used as the origin</summary>
        public long? StorageZoneId { get; set; }
        /// <summary>The type of the pull zone. Premium = 0, Volume = 1</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelType? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelType Type { get; set; }
#endif
        /// <summary>Determines if cache update is performed in the background.</summary>
        public bool? UseBackgroundUpdate { get; set; }
        /// <summary>Determines if we should use stale cache while the origin is offline</summary>
        public bool? UseStaleWhileOffline { get; set; }
        /// <summary>Determines if we should use stale cache while cache is updating</summary>
        public bool? UseStaleWhileUpdating { get; set; }
        /// <summary>Determines if the SSL certificate should be verified when connecting to the origin</summary>
        public bool? VerifyOriginSSL { get; set; }
        /// <summary>Determines if the zone token authentication security should be enabled</summary>
        public bool? ZoneSecurityEnabled { get; set; }
        /// <summary>Determines if the token authentication IP validation should be enabled</summary>
        public bool? ZoneSecurityIncludeHashRemoteIP { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AWSSigningEnabled", n => { AWSSigningEnabled = n.GetBoolValue(); } },
                { "AWSSigningKey", n => { AWSSigningKey = n.GetStringValue(); } },
                { "AWSSigningRegionName", n => { AWSSigningRegionName = n.GetStringValue(); } },
                { "AWSSigningSecret", n => { AWSSigningSecret = n.GetStringValue(); } },
                { "AccessControlOriginHeaderExtensions", n => { AccessControlOriginHeaderExtensions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "AddCanonicalHeader", n => { AddCanonicalHeader = n.GetBoolValue(); } },
                { "AddHostHeader", n => { AddHostHeader = n.GetBoolValue(); } },
                { "AllowedReferrers", n => { AllowedReferrers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "BlockNoneReferrer", n => { BlockNoneReferrer = n.GetBoolValue(); } },
                { "BlockPostRequests", n => { BlockPostRequests = n.GetBoolValue(); } },
                { "BlockRootPathAccess", n => { BlockRootPathAccess = n.GetBoolValue(); } },
                { "BlockedCountries", n => { BlockedCountries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "BlockedIps", n => { BlockedIps = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "BlockedReferrers", n => { BlockedReferrers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "BudgetRedirectedCountries", n => { BudgetRedirectedCountries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "BunnyAiImageBlueprints", n => { BunnyAiImageBlueprints = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.BunnyAiImageBlueprintModel>(global::Soenneker.Bunny.OpenApiClient.Models.BunnyAiImageBlueprintModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "BurstSize", n => { BurstSize = n.GetIntValue(); } },
                { "CacheControlBrowserMaxAgeOverride", n => { CacheControlBrowserMaxAgeOverride = n.GetLongValue(); } },
                { "CacheControlMaxAgeOverride", n => { CacheControlMaxAgeOverride = n.GetLongValue(); } },
                { "CacheControlPublicMaxAgeOverride", n => { CacheControlPublicMaxAgeOverride = n.GetLongValue(); } },
                { "CacheErrorResponses", n => { CacheErrorResponses = n.GetBoolValue(); } },
                { "CacheKeyHeaders", n => { CacheKeyHeaders = n.GetStringValue(); } },
                { "ConnectionLimitPerIPCount", n => { ConnectionLimitPerIPCount = n.GetIntValue(); } },
                { "CookieVaryParameters", n => { CookieVaryParameters = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "DisableCookies", n => { DisableCookies = n.GetBoolValue(); } },
                { "DisableLetsEncrypt", n => { DisableLetsEncrypt = n.GetBoolValue(); } },
                { "DnsOriginPort", n => { DnsOriginPort = n.GetIntValue(); } },
                { "DnsOriginScheme", n => { DnsOriginScheme = n.GetStringValue(); } },
                { "EdgeScriptExecutionPhase", n => { EdgeScriptExecutionPhase = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelEdgeScriptExecutionPhase>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelEdgeScriptExecutionPhase.CreateFromDiscriminatorValue); } },
                { "EdgeScriptId", n => { EdgeScriptId = n.GetLongValue(); } },
                { "EnableAccessControlOriginHeader", n => { EnableAccessControlOriginHeader = n.GetBoolValue(); } },
                { "EnableAutoSSL", n => { EnableAutoSSL = n.GetBoolValue(); } },
                { "EnableAvifVary", n => { EnableAvifVary = n.GetBoolValue(); } },
                { "EnableBunnyImageAi", n => { EnableBunnyImageAi = n.GetBoolValue(); } },
                { "EnableCacheSlice", n => { EnableCacheSlice = n.GetBoolValue(); } },
                { "EnableCookieVary", n => { EnableCookieVary = n.GetBoolValue(); } },
                { "EnableCountryCodeVary", n => { EnableCountryCodeVary = n.GetBoolValue(); } },
                { "EnableCountryStateCodeVary", n => { EnableCountryStateCodeVary = n.GetBoolValue(); } },
                { "EnableGeoZoneAF", n => { EnableGeoZoneAF = n.GetBoolValue(); } },
                { "EnableGeoZoneASIA", n => { EnableGeoZoneASIA = n.GetBoolValue(); } },
                { "EnableGeoZoneEU", n => { EnableGeoZoneEU = n.GetBoolValue(); } },
                { "EnableGeoZoneSA", n => { EnableGeoZoneSA = n.GetBoolValue(); } },
                { "EnableGeoZoneUS", n => { EnableGeoZoneUS = n.GetBoolValue(); } },
                { "EnableHostnameVary", n => { EnableHostnameVary = n.GetBoolValue(); } },
                { "EnableLogging", n => { EnableLogging = n.GetBoolValue(); } },
                { "EnableMobileVary", n => { EnableMobileVary = n.GetBoolValue(); } },
                { "EnableOriginShield", n => { EnableOriginShield = n.GetBoolValue(); } },
                { "EnableQueryStringOrdering", n => { EnableQueryStringOrdering = n.GetBoolValue(); } },
                { "EnableRequestCoalescing", n => { EnableRequestCoalescing = n.GetBoolValue(); } },
                { "EnableSafeHop", n => { EnableSafeHop = n.GetBoolValue(); } },
                { "EnableSmartCache", n => { EnableSmartCache = n.GetBoolValue(); } },
                { "EnableTLS1", n => { EnableTLS1 = n.GetBoolValue(); } },
                { "EnableTLS1_1", n => { EnableTLS11 = n.GetBoolValue(); } },
                { "EnableWebSockets", n => { EnableWebSockets = n.GetBoolValue(); } },
                { "EnableWebpVary", n => { EnableWebpVary = n.GetBoolValue(); } },
                { "ErrorPageCustomCode", n => { ErrorPageCustomCode = n.GetStringValue(); } },
                { "ErrorPageEnableCustomCode", n => { ErrorPageEnableCustomCode = n.GetBoolValue(); } },
                { "ErrorPageEnableStatuspageWidget", n => { ErrorPageEnableStatuspageWidget = n.GetBoolValue(); } },
                { "ErrorPageStatuspageCode", n => { ErrorPageStatuspageCode = n.GetStringValue(); } },
                { "ErrorPageWhitelabel", n => { ErrorPageWhitelabel = n.GetBoolValue(); } },
                { "FollowRedirects", n => { FollowRedirects = n.GetBoolValue(); } },
                { "IgnoreQueryStrings", n => { IgnoreQueryStrings = n.GetBoolValue(); } },
                { "IpFamilyPolicy", n => { IpFamilyPolicy = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelIpFamilyPolicy>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelIpFamilyPolicy.CreateFromDiscriminatorValue); } },
                { "LimitRateAfter", n => { LimitRateAfter = n.GetDoubleValue(); } },
                { "LimitRatePerSecond", n => { LimitRatePerSecond = n.GetIntValue(); } },
                { "LoadBalancerId", n => { LoadBalancerId = n.GetLongValue(); } },
                { "LogAnonymizationType", n => { LogAnonymizationType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogAnonymizationType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogAnonymizationType.CreateFromDiscriminatorValue); } },
                { "LogFormat", n => { LogFormat = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogFormat>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogFormat.CreateFromDiscriminatorValue); } },
                { "LogForwardingEnabled", n => { LogForwardingEnabled = n.GetBoolValue(); } },
                { "LogForwardingFormat", n => { LogForwardingFormat = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingFormat>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingFormat.CreateFromDiscriminatorValue); } },
                { "LogForwardingHostname", n => { LogForwardingHostname = n.GetStringValue(); } },
                { "LogForwardingPort", n => { LogForwardingPort = n.GetIntValue(); } },
                { "LogForwardingProtocol", n => { LogForwardingProtocol = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingProtocol>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingProtocol.CreateFromDiscriminatorValue); } },
                { "LogForwardingToken", n => { LogForwardingToken = n.GetStringValue(); } },
                { "LoggingIPAnonymizationEnabled", n => { LoggingIPAnonymizationEnabled = n.GetBoolValue(); } },
                { "LoggingSaveToStorage", n => { LoggingSaveToStorage = n.GetBoolValue(); } },
                { "LoggingStorageZoneId", n => { LoggingStorageZoneId = n.GetLongValue(); } },
                { "MagicContainersAppId", n => { MagicContainersAppId = n.GetStringValue(); } },
                { "MagicContainersEndpointId", n => { MagicContainersEndpointId = n.GetStringValue(); } },
                { "MaxWebSocketConnections", n => { MaxWebSocketConnections = n.GetIntValue(); } },
                { "MiddlewareScriptId", n => { MiddlewareScriptId = n.GetLongValue(); } },
                { "MonthlyBandwidthLimit", n => { MonthlyBandwidthLimit = n.GetLongValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "OptimizerAutomaticOptimizationEnabled", n => { OptimizerAutomaticOptimizationEnabled = n.GetBoolValue(); } },
                { "OptimizerClasses", n => { OptimizerClasses = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneOptimizerClassModel>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneOptimizerClassModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "OptimizerDesktopMaxWidth", n => { OptimizerDesktopMaxWidth = n.GetIntValue(); } },
                { "OptimizerEnableManipulationEngine", n => { OptimizerEnableManipulationEngine = n.GetBoolValue(); } },
                { "OptimizerEnableUpscaling", n => { OptimizerEnableUpscaling = n.GetBoolValue(); } },
                { "OptimizerEnableWebP", n => { OptimizerEnableWebP = n.GetBoolValue(); } },
                { "OptimizerEnabled", n => { OptimizerEnabled = n.GetBoolValue(); } },
                { "OptimizerForceClasses", n => { OptimizerForceClasses = n.GetBoolValue(); } },
                { "OptimizerHtmlToMarkdown", n => { OptimizerHtmlToMarkdown = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerHtmlToMarkdown>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerHtmlToMarkdown.CreateFromDiscriminatorValue); } },
                { "OptimizerImageQuality", n => { OptimizerImageQuality = n.GetIntValue(); } },
                { "OptimizerLlmsTxt", n => { OptimizerLlmsTxt = n.GetBoolValue(); } },
                { "OptimizerMinifyCSS", n => { OptimizerMinifyCSS = n.GetBoolValue(); } },
                { "OptimizerMinifyJavaScript", n => { OptimizerMinifyJavaScript = n.GetBoolValue(); } },
                { "OptimizerMobileImageQuality", n => { OptimizerMobileImageQuality = n.GetIntValue(); } },
                { "OptimizerMobileMaxWidth", n => { OptimizerMobileMaxWidth = n.GetIntValue(); } },
                { "OptimizerPrerenderHtml", n => { OptimizerPrerenderHtml = n.GetBoolValue(); } },
                { "OptimizerStaticHtmlEnabled", n => { OptimizerStaticHtmlEnabled = n.GetBoolValue(); } },
                { "OptimizerStaticHtmlWordPressBypassCookie", n => { OptimizerStaticHtmlWordPressBypassCookie = n.GetStringValue(); } },
                { "OptimizerStaticHtmlWordPressPath", n => { OptimizerStaticHtmlWordPressPath = n.GetStringValue(); } },
                { "OptimizerTunnelEnabled", n => { OptimizerTunnelEnabled = n.GetBoolValue(); } },
                { "OptimizerWatermarkEnabled", n => { OptimizerWatermarkEnabled = n.GetBoolValue(); } },
                { "OptimizerWatermarkMinImageSize", n => { OptimizerWatermarkMinImageSize = n.GetIntValue(); } },
                { "OptimizerWatermarkOffset", n => { OptimizerWatermarkOffset = n.GetDoubleValue(); } },
                { "OptimizerWatermarkPosition", n => { OptimizerWatermarkPosition = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerWatermarkPosition>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerWatermarkPosition.CreateFromDiscriminatorValue); } },
                { "OptimizerWatermarkUrl", n => { OptimizerWatermarkUrl = n.GetStringValue(); } },
                { "OriginConnectTimeout", n => { OriginConnectTimeout = n.GetIntValue(); } },
                { "OriginHostHeader", n => { OriginHostHeader = n.GetStringValue(); } },
                { "OriginResponseTimeout", n => { OriginResponseTimeout = n.GetIntValue(); } },
                { "OriginRetries", n => { OriginRetries = n.GetIntValue(); } },
                { "OriginRetry5XXResponses", n => { OriginRetry5XXResponses = n.GetBoolValue(); } },
                { "OriginRetryConnectionTimeout", n => { OriginRetryConnectionTimeout = n.GetBoolValue(); } },
                { "OriginRetryDelay", n => { OriginRetryDelay = n.GetIntValue(); } },
                { "OriginRetryResponseTimeout", n => { OriginRetryResponseTimeout = n.GetBoolValue(); } },
                { "OriginShieldEnableConcurrencyLimit", n => { OriginShieldEnableConcurrencyLimit = n.GetBoolValue(); } },
                { "OriginShieldMaxConcurrentRequests", n => { OriginShieldMaxConcurrentRequests = n.GetIntValue(); } },
                { "OriginShieldMaxQueuedRequests", n => { OriginShieldMaxQueuedRequests = n.GetIntValue(); } },
                { "OriginShieldQueueMaxWaitTime", n => { OriginShieldQueueMaxWaitTime = n.GetIntValue(); } },
                { "OriginShieldZoneCode", n => { OriginShieldZoneCode = n.GetStringValue(); } },
                { "OriginType", n => { OriginType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOriginType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOriginType.CreateFromDiscriminatorValue); } },
                { "OriginUrl", n => { OriginUrl = n.GetStringValue(); } },
                { "PermaCacheStorageZoneId", n => { PermaCacheStorageZoneId = n.GetLongValue(); } },
                { "PermaCacheType", n => { PermaCacheType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPermaCacheType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPermaCacheType.CreateFromDiscriminatorValue); } },
                { "PreloadingScreenCode", n => { PreloadingScreenCode = n.GetStringValue(); } },
                { "PreloadingScreenCodeEnabled", n => { PreloadingScreenCodeEnabled = n.GetBoolValue(); } },
                { "PreloadingScreenDelay", n => { PreloadingScreenDelay = n.GetIntValue(); } },
                { "PreloadingScreenEnabled", n => { PreloadingScreenEnabled = n.GetBoolValue(); } },
                { "PreloadingScreenLogoUrl", n => { PreloadingScreenLogoUrl = n.GetStringValue(); } },
                { "PreloadingScreenShowOnFirstVisit", n => { PreloadingScreenShowOnFirstVisit = n.GetBoolValue(); } },
                { "PreloadingScreenTheme", n => { PreloadingScreenTheme = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPreloadingScreenTheme>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPreloadingScreenTheme.CreateFromDiscriminatorValue); } },
                { "QueryStringVaryParameters", n => { QueryStringVaryParameters = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "RequestCoalescingTimeout", n => { RequestCoalescingTimeout = n.GetIntValue(); } },
                { "RequestLimit", n => { RequestLimit = n.GetIntValue(); } },
                { "RoutingFilters", n => { RoutingFilters = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "ShieldDDosProtectionEnabled", n => { ShieldDDosProtectionEnabled = n.GetBoolValue(); } },
                { "ShieldDDosProtectionType", n => { ShieldDDosProtectionType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelShieldDDosProtectionType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelShieldDDosProtectionType.CreateFromDiscriminatorValue); } },
                { "StickySessionClientHeaders", n => { StickySessionClientHeaders = n.GetStringValue(); } },
                { "StickySessionCookieName", n => { StickySessionCookieName = n.GetStringValue(); } },
                { "StickySessionType", n => { StickySessionType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelStickySessionType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelStickySessionType.CreateFromDiscriminatorValue); } },
                { "StorageZoneId", n => { StorageZoneId = n.GetLongValue(); } },
                { "Type", n => { Type = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelType>(global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelType.CreateFromDiscriminatorValue); } },
                { "UseBackgroundUpdate", n => { UseBackgroundUpdate = n.GetBoolValue(); } },
                { "UseStaleWhileOffline", n => { UseStaleWhileOffline = n.GetBoolValue(); } },
                { "UseStaleWhileUpdating", n => { UseStaleWhileUpdating = n.GetBoolValue(); } },
                { "VerifyOriginSSL", n => { VerifyOriginSSL = n.GetBoolValue(); } },
                { "ZoneSecurityEnabled", n => { ZoneSecurityEnabled = n.GetBoolValue(); } },
                { "ZoneSecurityIncludeHashRemoteIP", n => { ZoneSecurityIncludeHashRemoteIP = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("AccessControlOriginHeaderExtensions", AccessControlOriginHeaderExtensions);
            writer.WriteBoolValue("AddCanonicalHeader", AddCanonicalHeader);
            writer.WriteBoolValue("AddHostHeader", AddHostHeader);
            writer.WriteCollectionOfPrimitiveValues<string>("AllowedReferrers", AllowedReferrers);
            writer.WriteBoolValue("AWSSigningEnabled", AWSSigningEnabled);
            writer.WriteStringValue("AWSSigningKey", AWSSigningKey);
            writer.WriteStringValue("AWSSigningRegionName", AWSSigningRegionName);
            writer.WriteStringValue("AWSSigningSecret", AWSSigningSecret);
            writer.WriteCollectionOfPrimitiveValues<string>("BlockedCountries", BlockedCountries);
            writer.WriteCollectionOfPrimitiveValues<string>("BlockedIps", BlockedIps);
            writer.WriteCollectionOfPrimitiveValues<string>("BlockedReferrers", BlockedReferrers);
            writer.WriteBoolValue("BlockNoneReferrer", BlockNoneReferrer);
            writer.WriteBoolValue("BlockPostRequests", BlockPostRequests);
            writer.WriteBoolValue("BlockRootPathAccess", BlockRootPathAccess);
            writer.WriteCollectionOfPrimitiveValues<string>("BudgetRedirectedCountries", BudgetRedirectedCountries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.BunnyAiImageBlueprintModel>("BunnyAiImageBlueprints", BunnyAiImageBlueprints);
            writer.WriteIntValue("BurstSize", BurstSize);
            writer.WriteLongValue("CacheControlBrowserMaxAgeOverride", CacheControlBrowserMaxAgeOverride);
            writer.WriteLongValue("CacheControlMaxAgeOverride", CacheControlMaxAgeOverride);
            writer.WriteLongValue("CacheControlPublicMaxAgeOverride", CacheControlPublicMaxAgeOverride);
            writer.WriteBoolValue("CacheErrorResponses", CacheErrorResponses);
            writer.WriteStringValue("CacheKeyHeaders", CacheKeyHeaders);
            writer.WriteIntValue("ConnectionLimitPerIPCount", ConnectionLimitPerIPCount);
            writer.WriteCollectionOfPrimitiveValues<string>("CookieVaryParameters", CookieVaryParameters);
            writer.WriteBoolValue("DisableCookies", DisableCookies);
            writer.WriteBoolValue("DisableLetsEncrypt", DisableLetsEncrypt);
            writer.WriteIntValue("DnsOriginPort", DnsOriginPort);
            writer.WriteStringValue("DnsOriginScheme", DnsOriginScheme);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelEdgeScriptExecutionPhase>("EdgeScriptExecutionPhase", EdgeScriptExecutionPhase);
            writer.WriteLongValue("EdgeScriptId", EdgeScriptId);
            writer.WriteBoolValue("EnableAccessControlOriginHeader", EnableAccessControlOriginHeader);
            writer.WriteBoolValue("EnableAutoSSL", EnableAutoSSL);
            writer.WriteBoolValue("EnableAvifVary", EnableAvifVary);
            writer.WriteBoolValue("EnableBunnyImageAi", EnableBunnyImageAi);
            writer.WriteBoolValue("EnableCacheSlice", EnableCacheSlice);
            writer.WriteBoolValue("EnableCookieVary", EnableCookieVary);
            writer.WriteBoolValue("EnableCountryCodeVary", EnableCountryCodeVary);
            writer.WriteBoolValue("EnableCountryStateCodeVary", EnableCountryStateCodeVary);
            writer.WriteBoolValue("EnableGeoZoneAF", EnableGeoZoneAF);
            writer.WriteBoolValue("EnableGeoZoneASIA", EnableGeoZoneASIA);
            writer.WriteBoolValue("EnableGeoZoneEU", EnableGeoZoneEU);
            writer.WriteBoolValue("EnableGeoZoneSA", EnableGeoZoneSA);
            writer.WriteBoolValue("EnableGeoZoneUS", EnableGeoZoneUS);
            writer.WriteBoolValue("EnableHostnameVary", EnableHostnameVary);
            writer.WriteBoolValue("EnableLogging", EnableLogging);
            writer.WriteBoolValue("EnableMobileVary", EnableMobileVary);
            writer.WriteBoolValue("EnableOriginShield", EnableOriginShield);
            writer.WriteBoolValue("EnableQueryStringOrdering", EnableQueryStringOrdering);
            writer.WriteBoolValue("EnableRequestCoalescing", EnableRequestCoalescing);
            writer.WriteBoolValue("EnableSafeHop", EnableSafeHop);
            writer.WriteBoolValue("EnableSmartCache", EnableSmartCache);
            writer.WriteBoolValue("EnableTLS1", EnableTLS1);
            writer.WriteBoolValue("EnableTLS1_1", EnableTLS11);
            writer.WriteBoolValue("EnableWebpVary", EnableWebpVary);
            writer.WriteBoolValue("EnableWebSockets", EnableWebSockets);
            writer.WriteStringValue("ErrorPageCustomCode", ErrorPageCustomCode);
            writer.WriteBoolValue("ErrorPageEnableCustomCode", ErrorPageEnableCustomCode);
            writer.WriteBoolValue("ErrorPageEnableStatuspageWidget", ErrorPageEnableStatuspageWidget);
            writer.WriteStringValue("ErrorPageStatuspageCode", ErrorPageStatuspageCode);
            writer.WriteBoolValue("ErrorPageWhitelabel", ErrorPageWhitelabel);
            writer.WriteBoolValue("FollowRedirects", FollowRedirects);
            writer.WriteBoolValue("IgnoreQueryStrings", IgnoreQueryStrings);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelIpFamilyPolicy>("IpFamilyPolicy", IpFamilyPolicy);
            writer.WriteDoubleValue("LimitRateAfter", LimitRateAfter);
            writer.WriteIntValue("LimitRatePerSecond", LimitRatePerSecond);
            writer.WriteLongValue("LoadBalancerId", LoadBalancerId);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogAnonymizationType>("LogAnonymizationType", LogAnonymizationType);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogFormat>("LogFormat", LogFormat);
            writer.WriteBoolValue("LogForwardingEnabled", LogForwardingEnabled);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingFormat>("LogForwardingFormat", LogForwardingFormat);
            writer.WriteStringValue("LogForwardingHostname", LogForwardingHostname);
            writer.WriteIntValue("LogForwardingPort", LogForwardingPort);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelLogForwardingProtocol>("LogForwardingProtocol", LogForwardingProtocol);
            writer.WriteStringValue("LogForwardingToken", LogForwardingToken);
            writer.WriteBoolValue("LoggingIPAnonymizationEnabled", LoggingIPAnonymizationEnabled);
            writer.WriteBoolValue("LoggingSaveToStorage", LoggingSaveToStorage);
            writer.WriteLongValue("LoggingStorageZoneId", LoggingStorageZoneId);
            writer.WriteStringValue("MagicContainersAppId", MagicContainersAppId);
            writer.WriteStringValue("MagicContainersEndpointId", MagicContainersEndpointId);
            writer.WriteIntValue("MaxWebSocketConnections", MaxWebSocketConnections);
            writer.WriteLongValue("MiddlewareScriptId", MiddlewareScriptId);
            writer.WriteLongValue("MonthlyBandwidthLimit", MonthlyBandwidthLimit);
            writer.WriteStringValue("Name", Name);
            writer.WriteBoolValue("OptimizerAutomaticOptimizationEnabled", OptimizerAutomaticOptimizationEnabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneOptimizerClassModel>("OptimizerClasses", OptimizerClasses);
            writer.WriteIntValue("OptimizerDesktopMaxWidth", OptimizerDesktopMaxWidth);
            writer.WriteBoolValue("OptimizerEnabled", OptimizerEnabled);
            writer.WriteBoolValue("OptimizerEnableManipulationEngine", OptimizerEnableManipulationEngine);
            writer.WriteBoolValue("OptimizerEnableUpscaling", OptimizerEnableUpscaling);
            writer.WriteBoolValue("OptimizerEnableWebP", OptimizerEnableWebP);
            writer.WriteBoolValue("OptimizerForceClasses", OptimizerForceClasses);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerHtmlToMarkdown>("OptimizerHtmlToMarkdown", OptimizerHtmlToMarkdown);
            writer.WriteIntValue("OptimizerImageQuality", OptimizerImageQuality);
            writer.WriteBoolValue("OptimizerLlmsTxt", OptimizerLlmsTxt);
            writer.WriteBoolValue("OptimizerMinifyCSS", OptimizerMinifyCSS);
            writer.WriteBoolValue("OptimizerMinifyJavaScript", OptimizerMinifyJavaScript);
            writer.WriteIntValue("OptimizerMobileImageQuality", OptimizerMobileImageQuality);
            writer.WriteIntValue("OptimizerMobileMaxWidth", OptimizerMobileMaxWidth);
            writer.WriteBoolValue("OptimizerPrerenderHtml", OptimizerPrerenderHtml);
            writer.WriteBoolValue("OptimizerStaticHtmlEnabled", OptimizerStaticHtmlEnabled);
            writer.WriteStringValue("OptimizerStaticHtmlWordPressBypassCookie", OptimizerStaticHtmlWordPressBypassCookie);
            writer.WriteStringValue("OptimizerStaticHtmlWordPressPath", OptimizerStaticHtmlWordPressPath);
            writer.WriteBoolValue("OptimizerTunnelEnabled", OptimizerTunnelEnabled);
            writer.WriteBoolValue("OptimizerWatermarkEnabled", OptimizerWatermarkEnabled);
            writer.WriteIntValue("OptimizerWatermarkMinImageSize", OptimizerWatermarkMinImageSize);
            writer.WriteDoubleValue("OptimizerWatermarkOffset", OptimizerWatermarkOffset);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOptimizerWatermarkPosition>("OptimizerWatermarkPosition", OptimizerWatermarkPosition);
            writer.WriteStringValue("OptimizerWatermarkUrl", OptimizerWatermarkUrl);
            writer.WriteIntValue("OriginConnectTimeout", OriginConnectTimeout);
            writer.WriteStringValue("OriginHostHeader", OriginHostHeader);
            writer.WriteIntValue("OriginResponseTimeout", OriginResponseTimeout);
            writer.WriteIntValue("OriginRetries", OriginRetries);
            writer.WriteBoolValue("OriginRetry5XXResponses", OriginRetry5XXResponses);
            writer.WriteBoolValue("OriginRetryConnectionTimeout", OriginRetryConnectionTimeout);
            writer.WriteIntValue("OriginRetryDelay", OriginRetryDelay);
            writer.WriteBoolValue("OriginRetryResponseTimeout", OriginRetryResponseTimeout);
            writer.WriteBoolValue("OriginShieldEnableConcurrencyLimit", OriginShieldEnableConcurrencyLimit);
            writer.WriteIntValue("OriginShieldMaxConcurrentRequests", OriginShieldMaxConcurrentRequests);
            writer.WriteIntValue("OriginShieldMaxQueuedRequests", OriginShieldMaxQueuedRequests);
            writer.WriteIntValue("OriginShieldQueueMaxWaitTime", OriginShieldQueueMaxWaitTime);
            writer.WriteStringValue("OriginShieldZoneCode", OriginShieldZoneCode);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelOriginType>("OriginType", OriginType);
            writer.WriteStringValue("OriginUrl", OriginUrl);
            writer.WriteLongValue("PermaCacheStorageZoneId", PermaCacheStorageZoneId);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPermaCacheType>("PermaCacheType", PermaCacheType);
            writer.WriteStringValue("PreloadingScreenCode", PreloadingScreenCode);
            writer.WriteBoolValue("PreloadingScreenCodeEnabled", PreloadingScreenCodeEnabled);
            writer.WriteIntValue("PreloadingScreenDelay", PreloadingScreenDelay);
            writer.WriteBoolValue("PreloadingScreenEnabled", PreloadingScreenEnabled);
            writer.WriteStringValue("PreloadingScreenLogoUrl", PreloadingScreenLogoUrl);
            writer.WriteBoolValue("PreloadingScreenShowOnFirstVisit", PreloadingScreenShowOnFirstVisit);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelPreloadingScreenTheme>("PreloadingScreenTheme", PreloadingScreenTheme);
            writer.WriteCollectionOfPrimitiveValues<string>("QueryStringVaryParameters", QueryStringVaryParameters);
            writer.WriteIntValue("RequestCoalescingTimeout", RequestCoalescingTimeout);
            writer.WriteIntValue("RequestLimit", RequestLimit);
            writer.WriteCollectionOfPrimitiveValues<string>("RoutingFilters", RoutingFilters);
            writer.WriteBoolValue("ShieldDDosProtectionEnabled", ShieldDDosProtectionEnabled);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelShieldDDosProtectionType>("ShieldDDosProtectionType", ShieldDDosProtectionType);
            writer.WriteStringValue("StickySessionClientHeaders", StickySessionClientHeaders);
            writer.WriteStringValue("StickySessionCookieName", StickySessionCookieName);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelStickySessionType>("StickySessionType", StickySessionType);
            writer.WriteLongValue("StorageZoneId", StorageZoneId);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.PullZoneAddModelType>("Type", Type);
            writer.WriteBoolValue("UseBackgroundUpdate", UseBackgroundUpdate);
            writer.WriteBoolValue("UseStaleWhileOffline", UseStaleWhileOffline);
            writer.WriteBoolValue("UseStaleWhileUpdating", UseStaleWhileUpdating);
            writer.WriteBoolValue("VerifyOriginSSL", VerifyOriginSSL);
            writer.WriteBoolValue("ZoneSecurityEnabled", ZoneSecurityEnabled);
            writer.WriteBoolValue("ZoneSecurityIncludeHashRemoteIP", ZoneSecurityIncludeHashRemoteIP);
        }
    }
}
#pragma warning restore CS0618
