// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Severity : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper? SeverityOneOf1Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper SeverityOneOf1Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper? SeverityOneOf2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper SeverityOneOf2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper? SeverityOneOf3Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper SeverityOneOf3Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper? SeverityOneOf4Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper SeverityOneOf4Wrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.Severity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.Severity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Bunny.OpenApiClient.Models.Severity();
            if("SeverityOneOf1Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf1Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper();
            }
            else if("SeverityOneOf2Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf2Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper();
            }
            else if("SeverityOneOf3Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf3Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper();
            }
            else if("SeverityOneOf4Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf4Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SeverityOneOf1Wrapper != null)
            {
                return SeverityOneOf1Wrapper.GetFieldDeserializers();
            }
            else if(SeverityOneOf2Wrapper != null)
            {
                return SeverityOneOf2Wrapper.GetFieldDeserializers();
            }
            else if(SeverityOneOf3Wrapper != null)
            {
                return SeverityOneOf3Wrapper.GetFieldDeserializers();
            }
            else if(SeverityOneOf4Wrapper != null)
            {
                return SeverityOneOf4Wrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SeverityOneOf1Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1Wrapper>(null, SeverityOneOf1Wrapper);
            }
            else if(SeverityOneOf2Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2Wrapper>(null, SeverityOneOf2Wrapper);
            }
            else if(SeverityOneOf3Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3Wrapper>(null, SeverityOneOf3Wrapper);
            }
            else if(SeverityOneOf4Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4Wrapper>(null, SeverityOneOf4Wrapper);
            }
        }
    }
}
#pragma warning restore CS0618
