// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Severity : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1? SeverityOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1 SeverityOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2? SeverityOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2 SeverityOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3? SeverityOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3 SeverityOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4? SeverityOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4 SeverityOneOf4 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.Severity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.Severity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Bunny.OpenApiClient.Models.Severity();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf1 = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf2 = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf3 = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SeverityOneOf4 = new global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SeverityOneOf1 != null)
            {
                return SeverityOneOf1.GetFieldDeserializers();
            }
            else if(SeverityOneOf2 != null)
            {
                return SeverityOneOf2.GetFieldDeserializers();
            }
            else if(SeverityOneOf3 != null)
            {
                return SeverityOneOf3.GetFieldDeserializers();
            }
            else if(SeverityOneOf4 != null)
            {
                return SeverityOneOf4.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SeverityOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf1>(null, SeverityOneOf1);
            }
            else if(SeverityOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf2>(null, SeverityOneOf2);
            }
            else if(SeverityOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf3>(null, SeverityOneOf3);
            }
            else if(SeverityOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SeverityOneOf4>(null, SeverityOneOf4);
            }
        }
    }
}
#pragma warning restore CS0618
