// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper"/>, <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmartGenerateStatus : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper? SmartGenerateStatusOneOf1Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper SmartGenerateStatusOneOf1Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper? SmartGenerateStatusOneOf2Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper SmartGenerateStatusOneOf2Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper? SmartGenerateStatusOneOf3Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper SmartGenerateStatusOneOf3Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper? SmartGenerateStatusOneOf4Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper SmartGenerateStatusOneOf4Wrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper? SmartGenerateStatusOneOf5Wrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper SmartGenerateStatusOneOf5Wrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatus();
            if("SmartGenerateStatusOneOf1Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmartGenerateStatusOneOf1Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper();
            }
            else if("SmartGenerateStatusOneOf2Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmartGenerateStatusOneOf2Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper();
            }
            else if("SmartGenerateStatusOneOf3Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmartGenerateStatusOneOf3Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper();
            }
            else if("SmartGenerateStatusOneOf4Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmartGenerateStatusOneOf4Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper();
            }
            else if("SmartGenerateStatusOneOf5Wrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SmartGenerateStatusOneOf5Wrapper = new global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SmartGenerateStatusOneOf1Wrapper != null)
            {
                return SmartGenerateStatusOneOf1Wrapper.GetFieldDeserializers();
            }
            else if(SmartGenerateStatusOneOf2Wrapper != null)
            {
                return SmartGenerateStatusOneOf2Wrapper.GetFieldDeserializers();
            }
            else if(SmartGenerateStatusOneOf3Wrapper != null)
            {
                return SmartGenerateStatusOneOf3Wrapper.GetFieldDeserializers();
            }
            else if(SmartGenerateStatusOneOf4Wrapper != null)
            {
                return SmartGenerateStatusOneOf4Wrapper.GetFieldDeserializers();
            }
            else if(SmartGenerateStatusOneOf5Wrapper != null)
            {
                return SmartGenerateStatusOneOf5Wrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SmartGenerateStatusOneOf1Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf1Wrapper>(null, SmartGenerateStatusOneOf1Wrapper);
            }
            else if(SmartGenerateStatusOneOf2Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf2Wrapper>(null, SmartGenerateStatusOneOf2Wrapper);
            }
            else if(SmartGenerateStatusOneOf3Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf3Wrapper>(null, SmartGenerateStatusOneOf3Wrapper);
            }
            else if(SmartGenerateStatusOneOf4Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf4Wrapper>(null, SmartGenerateStatusOneOf4Wrapper);
            }
            else if(SmartGenerateStatusOneOf5Wrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.SmartGenerateStatusOneOf5Wrapper>(null, SmartGenerateStatusOneOf5Wrapper);
            }
        }
    }
}
#pragma warning restore CS0618
