// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StatisticsModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The median response time origin</summary>
        public int? AverageOriginResponseTime { get; set; }
        /// <summary>The constructed cached bandwdidth used chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthCachedChart? BandwidthCachedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthCachedChart BandwidthCachedChart { get; set; }
#endif
        /// <summary>The constructed bandwdidth used chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthUsedChart? BandwidthUsedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthUsedChart BandwidthUsedChart { get; set; }
#endif
        /// <summary>The average cache hit rate in the response in the given time range</summary>
        public double? CacheHitRate { get; set; }
        /// <summary>The constructed cache hit rate chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelCacheHitRateChart? CacheHitRateChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelCacheHitRateChart CacheHitRateChart { get; set; }
#endif
        /// <summary>The constructed 3XX error responses chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError3XxChart? Error3xxChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError3XxChart Error3xxChart { get; set; }
#endif
        /// <summary>The constructed 4XX error responses chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError4XxChart? Error4xxChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError4XxChart Error4xxChart { get; set; }
#endif
        /// <summary>The constructed 5XX error responses chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError5XxChart? Error5xxChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError5XxChart Error5xxChart { get; set; }
#endif
        /// <summary>The geo traffic distribution data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelGeoTrafficDistribution? GeoTrafficDistribution { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelGeoTrafficDistribution GeoTrafficDistribution { get; set; }
#endif
        /// <summary>The constructed origin response time chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginResponseTimeChart? OriginResponseTimeChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginResponseTimeChart OriginResponseTimeChart { get; set; }
#endif
        /// <summary>The constructed origin shield bandwdidth used chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldBandwidthUsedChart? OriginShieldBandwidthUsedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldBandwidthUsedChart OriginShieldBandwidthUsedChart { get; set; }
#endif
        /// <summary>The constructed origin shield internal bandwdidth used chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldInternalBandwidthUsedChart? OriginShieldInternalBandwidthUsedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldInternalBandwidthUsedChart OriginShieldInternalBandwidthUsedChart { get; set; }
#endif
        /// <summary>The constructed origin traffic used chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginTrafficChart? OriginTrafficChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginTrafficChart OriginTrafficChart { get; set; }
#endif
        /// <summary>The constructed uncached requests served chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelPullRequestsPulledChart? PullRequestsPulledChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelPullRequestsPulledChart PullRequestsPulledChart { get; set; }
#endif
        /// <summary>The constructed requests served chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelRequestsServedChart? RequestsServedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelRequestsServedChart RequestsServedChart { get; set; }
#endif
        /// <summary>The total bandwidth used by the response in the given time range</summary>
        public long? TotalBandwidthUsed { get; set; }
        /// <summary>The total amount of traffic received from the origin</summary>
        public long? TotalOriginTraffic { get; set; }
        /// <summary>The total requests served by the response in the given time range</summary>
        public long? TotalRequestsServed { get; set; }
        /// <summary>The constructed user balance history chart data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelUserBalanceHistoryChart? UserBalanceHistoryChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelUserBalanceHistoryChart UserBalanceHistoryChart { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AverageOriginResponseTime", n => { AverageOriginResponseTime = n.GetIntValue(); } },
                { "BandwidthCachedChart", n => { BandwidthCachedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthCachedChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthCachedChart.CreateFromDiscriminatorValue); } },
                { "BandwidthUsedChart", n => { BandwidthUsedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthUsedChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthUsedChart.CreateFromDiscriminatorValue); } },
                { "CacheHitRate", n => { CacheHitRate = n.GetDoubleValue(); } },
                { "CacheHitRateChart", n => { CacheHitRateChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelCacheHitRateChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelCacheHitRateChart.CreateFromDiscriminatorValue); } },
                { "Error3xxChart", n => { Error3xxChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError3XxChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError3XxChart.CreateFromDiscriminatorValue); } },
                { "Error4xxChart", n => { Error4xxChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError4XxChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError4XxChart.CreateFromDiscriminatorValue); } },
                { "Error5xxChart", n => { Error5xxChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError5XxChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError5XxChart.CreateFromDiscriminatorValue); } },
                { "GeoTrafficDistribution", n => { GeoTrafficDistribution = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelGeoTrafficDistribution>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelGeoTrafficDistribution.CreateFromDiscriminatorValue); } },
                { "OriginResponseTimeChart", n => { OriginResponseTimeChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginResponseTimeChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginResponseTimeChart.CreateFromDiscriminatorValue); } },
                { "OriginShieldBandwidthUsedChart", n => { OriginShieldBandwidthUsedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldBandwidthUsedChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldBandwidthUsedChart.CreateFromDiscriminatorValue); } },
                { "OriginShieldInternalBandwidthUsedChart", n => { OriginShieldInternalBandwidthUsedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldInternalBandwidthUsedChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldInternalBandwidthUsedChart.CreateFromDiscriminatorValue); } },
                { "OriginTrafficChart", n => { OriginTrafficChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginTrafficChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginTrafficChart.CreateFromDiscriminatorValue); } },
                { "PullRequestsPulledChart", n => { PullRequestsPulledChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelPullRequestsPulledChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelPullRequestsPulledChart.CreateFromDiscriminatorValue); } },
                { "RequestsServedChart", n => { RequestsServedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelRequestsServedChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelRequestsServedChart.CreateFromDiscriminatorValue); } },
                { "TotalBandwidthUsed", n => { TotalBandwidthUsed = n.GetLongValue(); } },
                { "TotalOriginTraffic", n => { TotalOriginTraffic = n.GetLongValue(); } },
                { "TotalRequestsServed", n => { TotalRequestsServed = n.GetLongValue(); } },
                { "UserBalanceHistoryChart", n => { UserBalanceHistoryChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelUserBalanceHistoryChart>(global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelUserBalanceHistoryChart.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("AverageOriginResponseTime", AverageOriginResponseTime);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthCachedChart>("BandwidthCachedChart", BandwidthCachedChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelBandwidthUsedChart>("BandwidthUsedChart", BandwidthUsedChart);
            writer.WriteDoubleValue("CacheHitRate", CacheHitRate);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelCacheHitRateChart>("CacheHitRateChart", CacheHitRateChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError3XxChart>("Error3xxChart", Error3xxChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError4XxChart>("Error4xxChart", Error4xxChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelError5XxChart>("Error5xxChart", Error5xxChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelGeoTrafficDistribution>("GeoTrafficDistribution", GeoTrafficDistribution);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginResponseTimeChart>("OriginResponseTimeChart", OriginResponseTimeChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldBandwidthUsedChart>("OriginShieldBandwidthUsedChart", OriginShieldBandwidthUsedChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginShieldInternalBandwidthUsedChart>("OriginShieldInternalBandwidthUsedChart", OriginShieldInternalBandwidthUsedChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelOriginTrafficChart>("OriginTrafficChart", OriginTrafficChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelPullRequestsPulledChart>("PullRequestsPulledChart", PullRequestsPulledChart);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelRequestsServedChart>("RequestsServedChart", RequestsServedChart);
            writer.WriteLongValue("TotalBandwidthUsed", TotalBandwidthUsed);
            writer.WriteLongValue("TotalOriginTraffic", TotalOriginTraffic);
            writer.WriteLongValue("TotalRequestsServed", TotalRequestsServed);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.StatisticsModelUserBalanceHistoryChart>("UserBalanceHistoryChart", UserBalanceHistoryChart);
        }
    }
}
#pragma warning restore CS0618
