// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// The response payload. Some endpoints also populate this with error details when Success is false — see the endpoint&apos;s own response documentation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusModelOfResolutionsCleanupModelAllOf2Data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The video&apos;s available resolutions after this cleanup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AvailableResolutionsAfter { get; set; }
#nullable restore
#else
        public List<string> AvailableResolutionsAfter { get; set; }
#endif
        /// <summary>Whether the original uploaded source file was deleted from storage as part of this operation.</summary>
        public bool? DeletedOriginal { get; set; }
        /// <summary>Whether at least one of the storage objects in StorageObjectsToDelete was actually deleted (always false when dryRun is true). Individual objects can still have failed to delete — their failures are logged and do not clear this flag — so this confirms the cleanup did something, not that it removed everything listed.</summary>
        public bool? DeletedStorageObjects { get; set; }
        /// <summary>Whether the HLS master playlist was rewritten to remove the deleted resolutions.</summary>
        public bool? ModifiedPlaylist { get; set; }
        /// <summary>Resolutions selected for removal as part of this cleanup, across the HLS playlist, object storage, and MP4 fallback set. Populated even when dryRun is true or an individual deletion fails — see UpdatedAvailableResolutions/ModifiedPlaylist/DeletedStorageObjects for what was actually changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResolutionsToDelete { get; set; }
#nullable restore
#else
        public List<string> ResolutionsToDelete { get; set; }
#endif
        /// <summary>Resolutions selected for removal from the MP4 fallback set. Populated even when dryRun is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResolutionsToDeleteFromMp4 { get; set; }
#nullable restore
#else
        public List<string> ResolutionsToDeleteFromMp4 { get; set; }
#endif
        /// <summary>Resolutions selected for removal from the HLS master playlist. Populated even when dryRun is true.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResolutionsToDeleteFromPlaylist { get; set; }
#nullable restore
#else
        public List<string> ResolutionsToDeleteFromPlaylist { get; set; }
#endif
        /// <summary>Resolutions selected for removal from object storage. Populated even when dryRun is true or an individual deletion fails.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ResolutionsToDeleteFromStorage { get; set; }
#nullable restore
#else
        public List<string> ResolutionsToDeleteFromStorage { get; set; }
#endif
        /// <summary>Storage object paths selected for deletion as part of this cleanup. These are candidates, not confirmations: the list is populated even when dryRun is true or when an individual deletion fails — see DeletedStorageObjects for whether at least one deletion actually succeeded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StorageObjectsToDelete { get; set; }
#nullable restore
#else
        public List<string> StorageObjectsToDelete { get; set; }
#endif
        /// <summary>Whether the video&apos;s AvailableResolutions field was rewritten as part of this cleanup.</summary>
        public bool? UpdatedAvailableResolutions { get; set; }
        /// <summary>The GUID of the video.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoId { get; set; }
#nullable restore
#else
        public string VideoId { get; set; }
#endif
        /// <summary>The ID of the video library.</summary>
        public long? VideoLibraryId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Models.StatusModelOfResolutionsCleanupModelAllOf2Data"/> and sets the default values.
        /// </summary>
        public StatusModelOfResolutionsCleanupModelAllOf2Data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.StatusModelOfResolutionsCleanupModelAllOf2Data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.StatusModelOfResolutionsCleanupModelAllOf2Data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.StatusModelOfResolutionsCleanupModelAllOf2Data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "availableResolutionsAfter", n => { AvailableResolutionsAfter = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "deletedOriginal", n => { DeletedOriginal = n.GetBoolValue(); } },
                { "deletedStorageObjects", n => { DeletedStorageObjects = n.GetBoolValue(); } },
                { "modifiedPlaylist", n => { ModifiedPlaylist = n.GetBoolValue(); } },
                { "resolutionsToDelete", n => { ResolutionsToDelete = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "resolutionsToDeleteFromMp4", n => { ResolutionsToDeleteFromMp4 = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "resolutionsToDeleteFromPlaylist", n => { ResolutionsToDeleteFromPlaylist = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "resolutionsToDeleteFromStorage", n => { ResolutionsToDeleteFromStorage = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "storageObjectsToDelete", n => { StorageObjectsToDelete = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updatedAvailableResolutions", n => { UpdatedAvailableResolutions = n.GetBoolValue(); } },
                { "videoId", n => { VideoId = n.GetStringValue(); } },
                { "videoLibraryId", n => { VideoLibraryId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("availableResolutionsAfter", AvailableResolutionsAfter);
            writer.WriteBoolValue("deletedOriginal", DeletedOriginal);
            writer.WriteBoolValue("deletedStorageObjects", DeletedStorageObjects);
            writer.WriteBoolValue("modifiedPlaylist", ModifiedPlaylist);
            writer.WriteCollectionOfPrimitiveValues<string>("resolutionsToDelete", ResolutionsToDelete);
            writer.WriteCollectionOfPrimitiveValues<string>("resolutionsToDeleteFromMp4", ResolutionsToDeleteFromMp4);
            writer.WriteCollectionOfPrimitiveValues<string>("resolutionsToDeleteFromPlaylist", ResolutionsToDeleteFromPlaylist);
            writer.WriteCollectionOfPrimitiveValues<string>("resolutionsToDeleteFromStorage", ResolutionsToDeleteFromStorage);
            writer.WriteCollectionOfPrimitiveValues<string>("storageObjectsToDelete", StorageObjectsToDelete);
            writer.WriteBoolValue("updatedAvailableResolutions", UpdatedAvailableResolutions);
            writer.WriteStringValue("videoId", VideoId);
            writer.WriteLongValue("videoLibraryId", VideoLibraryId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
