// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateDnsZoneModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Sets the certificate private key type for wildcard certificates for this zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelCertificateKeyType? CertificateKeyType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelCertificateKeyType CertificateKeyType { get; set; }
#endif
        /// <summary>The CustomNameserversEnabled property</summary>
        public bool? CustomNameserversEnabled { get; set; }
        /// <summary>Gets the log anonymization type for this zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelLogAnonymizationType? LogAnonymizationType { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelLogAnonymizationType LogAnonymizationType { get; set; }
#endif
        /// <summary>The LoggingEnabled property</summary>
        public bool? LoggingEnabled { get; set; }
        /// <summary>Determines if the log anonoymization should be enabled</summary>
        public bool? LoggingIPAnonymizationEnabled { get; set; }
        /// <summary>The Nameserver1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nameserver1 { get; set; }
#nullable restore
#else
        public string Nameserver1 { get; set; }
#endif
        /// <summary>The Nameserver2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nameserver2 { get; set; }
#nullable restore
#else
        public string Nameserver2 { get; set; }
#endif
        /// <summary>The SoaEmail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoaEmail { get; set; }
#nullable restore
#else
        public string SoaEmail { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "CertificateKeyType", n => { CertificateKeyType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelCertificateKeyType>(global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelCertificateKeyType.CreateFromDiscriminatorValue); } },
                { "CustomNameserversEnabled", n => { CustomNameserversEnabled = n.GetBoolValue(); } },
                { "LogAnonymizationType", n => { LogAnonymizationType = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelLogAnonymizationType>(global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelLogAnonymizationType.CreateFromDiscriminatorValue); } },
                { "LoggingEnabled", n => { LoggingEnabled = n.GetBoolValue(); } },
                { "LoggingIPAnonymizationEnabled", n => { LoggingIPAnonymizationEnabled = n.GetBoolValue(); } },
                { "Nameserver1", n => { Nameserver1 = n.GetStringValue(); } },
                { "Nameserver2", n => { Nameserver2 = n.GetStringValue(); } },
                { "SoaEmail", n => { SoaEmail = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelCertificateKeyType>("CertificateKeyType", CertificateKeyType);
            writer.WriteBoolValue("CustomNameserversEnabled", CustomNameserversEnabled);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.UpdateDnsZoneModelLogAnonymizationType>("LogAnonymizationType", LogAnonymizationType);
            writer.WriteBoolValue("LoggingEnabled", LoggingEnabled);
            writer.WriteBoolValue("LoggingIPAnonymizationEnabled", LoggingIPAnonymizationEnabled);
            writer.WriteStringValue("Nameserver1", Nameserver1);
            writer.WriteStringValue("Nameserver2", Nameserver2);
            writer.WriteStringValue("SoaEmail", SoaEmail);
        }
    }
}
#pragma warning restore CS0618
