// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateUploadScanningConfigurationRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>0 = Disabled1 = Log2 = Block</summary>
        public int? AntivirusScanningMode { get; set; }
        /// <summary>0 = Disabled1 = Log2 = Block</summary>
        public int? CsamScanningMode { get; set; }
        /// <summary>The isEnabled property</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>The shieldZoneId property</summary>
        public int? ShieldZoneId { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.UpdateUploadScanningConfigurationRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.UpdateUploadScanningConfigurationRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.UpdateUploadScanningConfigurationRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "antivirusScanningMode", n => { AntivirusScanningMode = n.GetIntValue(); } },
                { "csamScanningMode", n => { CsamScanningMode = n.GetIntValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "shieldZoneId", n => { ShieldZoneId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("antivirusScanningMode", AntivirusScanningMode);
            writer.WriteIntValue("csamScanningMode", CsamScanningMode);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteIntValue("shieldZoneId", ShieldZoneId);
        }
    }
}
#pragma warning restore CS0618
