// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    /// <summary>
    /// Combined premium and free encoding statistics for the selected period.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VideoEncodingStatisticsModelTotal : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Encoding seconds grouped by encoding type: &apos;jit&apos; for just-in-time encodes, &apos;standard&apos; for full encodes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByJit? ByJit { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByJit ByJit { get; set; }
#endif
        /// <summary>Encoding seconds grouped by the video&apos;s highest output resolution. 0 means the resolution was unknown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByResolution? ByResolution { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByResolution ByResolution { get; set; }
#endif
        /// <summary>Encoding seconds grouped by output video codec (H264, VP9, HEVC, AV1).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByVideoCodec? ByVideoCodec { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByVideoCodec ByVideoCodec { get; set; }
#endif
        /// <summary>Billable (normalized) encoding seconds over time, grouped hourly or daily in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalNormalizedChart? NormalizedChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalNormalizedChart NormalizedChart { get; set; }
#endif
        /// <summary>Billable encoding seconds in the selected period: counted per output codec and weighted by the video&apos;s highest resolution (x0.5 below 720p, x1 up to 1080p, x3 above).</summary>
        public long? NormalizedTotal { get; set; }
        /// <summary>Encoded output seconds over time, grouped hourly or daily in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalOutputChart? OutputChart { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalOutputChart OutputChart { get; set; }
#endif
        /// <summary>Encoded output seconds in the selected period: video length counted once per output codec, without resolution weighting.</summary>
        public long? OutputTotal { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotal"/> and sets the default values.
        /// </summary>
        public VideoEncodingStatisticsModelTotal()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotal"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotal CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotal();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "byJit", n => { ByJit = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByJit>(global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByJit.CreateFromDiscriminatorValue); } },
                { "byResolution", n => { ByResolution = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByResolution>(global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByResolution.CreateFromDiscriminatorValue); } },
                { "byVideoCodec", n => { ByVideoCodec = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByVideoCodec>(global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByVideoCodec.CreateFromDiscriminatorValue); } },
                { "normalizedChart", n => { NormalizedChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalNormalizedChart>(global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalNormalizedChart.CreateFromDiscriminatorValue); } },
                { "normalizedTotal", n => { NormalizedTotal = n.GetLongValue(); } },
                { "outputChart", n => { OutputChart = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalOutputChart>(global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalOutputChart.CreateFromDiscriminatorValue); } },
                { "outputTotal", n => { OutputTotal = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByJit>("byJit", ByJit);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByResolution>("byResolution", ByResolution);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalByVideoCodec>("byVideoCodec", ByVideoCodec);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalNormalizedChart>("normalizedChart", NormalizedChart);
            writer.WriteLongValue("normalizedTotal", NormalizedTotal);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.VideoEncodingStatisticsModelTotalOutputChart>("outputChart", OutputChart);
            writer.WriteLongValue("outputTotal", OutputTotal);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
