// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class VideoLibraryCreateModel : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>(Optional) Determines if direct play URLs should be enabled for the library</summary>
        public bool? AllowDirectPlay { get; set; }
        /// <summary>(Optional) Enables Early Play. Enabling this also exposes originals via CDN settings consistent with the video library update API.</summary>
        public bool? AllowEarlyPlay { get; set; }
        /// <summary>(Optional) Determines if requests without a referer should be blocked.</summary>
        public bool? BlockNoneReferrer { get; set; }
        /// <summary>&quot;(Optional) Sets the enabled resolutions for the transcoding. At least one resolution should be enabled. Possible values: 240p, 360p, 480p, 720p, 1080p, 1440p, 2160p&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnabledResolutions { get; set; }
#nullable restore
#else
        public string EnabledResolutions { get; set; }
#endif
        /// <summary>(Optional) Determines if MP4 fallback should be enabled for this library.</summary>
        public bool? EnableMP4Fallback { get; set; }
        /// <summary>(Optional) Determines if multiple output audio track support is enabled on video library.</summary>
        public bool? EnableMultiAudioTrackSupport { get; set; }
        /// <summary>(Optional) Enables automatic audio transcribing for this library.</summary>
        public bool? EnableTranscribing { get; set; }
        /// <summary>(Optional) Determines if automatic transcribing chapters generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.</summary>
        public bool? EnableTranscribingChaptersGeneration { get; set; }
        /// <summary>(Optional) Determines if automatic transcribing description generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.</summary>
        public bool? EnableTranscribingDescriptionGeneration { get; set; }
        /// <summary>(Optional) Determines if automatic transcribing moments generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.</summary>
        public bool? EnableTranscribingMomentsGeneration { get; set; }
        /// <summary>(Optional) Determines if automatic transcribing title generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.</summary>
        public bool? EnableTranscribingTitleGeneration { get; set; }
        /// <summary>(Optional) Defines encoding tier. Premium is a paid tier that offers prioritized encoding and extra codec support.</summary>
        public int? EncodingTier { get; set; }
        /// <summary>(Optional) Determines whether JIT encoding should be used for the library. Supported in premium encoding only.</summary>
        public bool? JitEncodingEnabled { get; set; }
        /// <summary>(Optional) Determines if the original file should be kept after the video is processed.</summary>
        public bool? KeepOriginalFiles { get; set; }
        /// <summary>The name of the Video Library.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>(Optional) Specifies which video codecs are used for encoding, provided as a comma-separated (CSV) string. Free encoding tier supports only x264. A premium encoding tier adds support for vp9, hevc, and av1.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputCodecs { get; set; }
#nullable restore
#else
        public string OutputCodecs { get; set; }
#endif
        /// <summary>(Optional) Sets player version used for this library</summary>
        public int? PlayerVersion { get; set; }
        /// <summary>The geo-replication regions of the underlying storage zone</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReplicationRegions { get; set; }
#nullable restore
#else
        public List<string> ReplicationRegions { get; set; }
#endif
        /// <summary>(Optional) Languages that captions will be automatically transcribed to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TranscribingCaptionLanguages { get; set; }
#nullable restore
#else
        public List<string> TranscribingCaptionLanguages { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.VideoLibraryCreateModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.VideoLibraryCreateModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.VideoLibraryCreateModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AllowDirectPlay", n => { AllowDirectPlay = n.GetBoolValue(); } },
                { "AllowEarlyPlay", n => { AllowEarlyPlay = n.GetBoolValue(); } },
                { "BlockNoneReferrer", n => { BlockNoneReferrer = n.GetBoolValue(); } },
                { "EnableMP4Fallback", n => { EnableMP4Fallback = n.GetBoolValue(); } },
                { "EnableMultiAudioTrackSupport", n => { EnableMultiAudioTrackSupport = n.GetBoolValue(); } },
                { "EnableTranscribing", n => { EnableTranscribing = n.GetBoolValue(); } },
                { "EnableTranscribingChaptersGeneration", n => { EnableTranscribingChaptersGeneration = n.GetBoolValue(); } },
                { "EnableTranscribingDescriptionGeneration", n => { EnableTranscribingDescriptionGeneration = n.GetBoolValue(); } },
                { "EnableTranscribingMomentsGeneration", n => { EnableTranscribingMomentsGeneration = n.GetBoolValue(); } },
                { "EnableTranscribingTitleGeneration", n => { EnableTranscribingTitleGeneration = n.GetBoolValue(); } },
                { "EnabledResolutions", n => { EnabledResolutions = n.GetStringValue(); } },
                { "EncodingTier", n => { EncodingTier = n.GetIntValue(); } },
                { "JitEncodingEnabled", n => { JitEncodingEnabled = n.GetBoolValue(); } },
                { "KeepOriginalFiles", n => { KeepOriginalFiles = n.GetBoolValue(); } },
                { "Name", n => { Name = n.GetStringValue(); } },
                { "OutputCodecs", n => { OutputCodecs = n.GetStringValue(); } },
                { "PlayerVersion", n => { PlayerVersion = n.GetIntValue(); } },
                { "ReplicationRegions", n => { ReplicationRegions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "TranscribingCaptionLanguages", n => { TranscribingCaptionLanguages = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("AllowDirectPlay", AllowDirectPlay);
            writer.WriteBoolValue("AllowEarlyPlay", AllowEarlyPlay);
            writer.WriteBoolValue("BlockNoneReferrer", BlockNoneReferrer);
            writer.WriteStringValue("EnabledResolutions", EnabledResolutions);
            writer.WriteBoolValue("EnableMP4Fallback", EnableMP4Fallback);
            writer.WriteBoolValue("EnableMultiAudioTrackSupport", EnableMultiAudioTrackSupport);
            writer.WriteBoolValue("EnableTranscribing", EnableTranscribing);
            writer.WriteBoolValue("EnableTranscribingChaptersGeneration", EnableTranscribingChaptersGeneration);
            writer.WriteBoolValue("EnableTranscribingDescriptionGeneration", EnableTranscribingDescriptionGeneration);
            writer.WriteBoolValue("EnableTranscribingMomentsGeneration", EnableTranscribingMomentsGeneration);
            writer.WriteBoolValue("EnableTranscribingTitleGeneration", EnableTranscribingTitleGeneration);
            writer.WriteIntValue("EncodingTier", EncodingTier);
            writer.WriteBoolValue("JitEncodingEnabled", JitEncodingEnabled);
            writer.WriteBoolValue("KeepOriginalFiles", KeepOriginalFiles);
            writer.WriteStringValue("Name", Name);
            writer.WriteStringValue("OutputCodecs", OutputCodecs);
            writer.WriteIntValue("PlayerVersion", PlayerVersion);
            writer.WriteCollectionOfPrimitiveValues<string>("ReplicationRegions", ReplicationRegions);
            writer.WriteCollectionOfPrimitiveValues<string>("TranscribingCaptionLanguages", TranscribingCaptionLanguages);
        }
    }
}
#pragma warning restore CS0618
