// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WafLoggingResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The continuationToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContinuationToken { get; set; }
#nullable restore
#else
        public string ContinuationToken { get; set; }
#endif
        /// <summary>Generic response object containing status information for API operations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse? ErrorResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse ErrorResponse { get; set; }
#endif
        /// <summary>The hasMoreData property</summary>
        public bool? HasMoreData { get; set; }
        /// <summary>The logs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Bunny.OpenApiClient.Models.Log>? Logs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Bunny.OpenApiClient.Models.Log> Logs { get; set; }
#endif
        /// <summary>The startToken property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartToken { get; set; }
#nullable restore
#else
        public string StartToken { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.WafLoggingResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.WafLoggingResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.WafLoggingResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "continuationToken", n => { ContinuationToken = n.GetStringValue(); } },
                { "errorResponse", n => { ErrorResponse = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse>(global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse.CreateFromDiscriminatorValue); } },
                { "hasMoreData", n => { HasMoreData = n.GetBoolValue(); } },
                { "logs", n => { Logs = n.GetCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.Log>(global::Soenneker.Bunny.OpenApiClient.Models.Log.CreateFromDiscriminatorValue)?.AsList(); } },
                { "startToken", n => { StartToken = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("continuationToken", ContinuationToken);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.GenericRequestResponse>("errorResponse", ErrorResponse);
            writer.WriteBoolValue("hasMoreData", HasMoreData);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Bunny.OpenApiClient.Models.Log>("logs", Logs);
            writer.WriteStringValue("startToken", StartToken);
        }
    }
}
#pragma warning restore CS0618
