// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Bunny.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WafRuleMetrics : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The blockedRequests property</summary>
        public int? BlockedRequests { get; set; }
        /// <summary>The challengedRequests property</summary>
        public int? ChallengedRequests { get; set; }
        /// <summary>The loggedRequests property</summary>
        public int? LoggedRequests { get; set; }
        /// <summary>The overviewPastTwentyEightDays property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetricsOverviewPastTwentyEightDays? OverviewPastTwentyEightDays { get; set; }
#nullable restore
#else
        public global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetricsOverviewPastTwentyEightDays OverviewPastTwentyEightDays { get; set; }
#endif
        /// <summary>The totalTriggers property</summary>
        public int? TotalTriggers { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetrics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetrics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetrics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockedRequests", n => { BlockedRequests = n.GetIntValue(); } },
                { "challengedRequests", n => { ChallengedRequests = n.GetIntValue(); } },
                { "loggedRequests", n => { LoggedRequests = n.GetIntValue(); } },
                { "overviewPastTwentyEightDays", n => { OverviewPastTwentyEightDays = n.GetObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetricsOverviewPastTwentyEightDays>(global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetricsOverviewPastTwentyEightDays.CreateFromDiscriminatorValue); } },
                { "totalTriggers", n => { TotalTriggers = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("blockedRequests", BlockedRequests);
            writer.WriteIntValue("challengedRequests", ChallengedRequests);
            writer.WriteIntValue("loggedRequests", LoggedRequests);
            writer.WriteObjectValue<global::Soenneker.Bunny.OpenApiClient.Models.WafRuleMetricsOverviewPastTwentyEightDays>("overviewPastTwentyEightDays", OverviewPastTwentyEightDays);
            writer.WriteIntValue("totalTriggers", TotalTriggers);
        }
    }
}
#pragma warning restore CS0618
