// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithPullZoneIdLog;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Bunny.OpenApiClient.CdnLogging.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \cdn-logging\{date}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDateItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cdn-logging/{date}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithDateItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDateItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cdn-logging/{date}", rawUrl)
        {
        }
        /// <summary>
        /// Builds and executes requests for operations under \cdn-logging\{date}\{pullZoneId}.log
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithPullZoneIdLog.WithPullZoneIdLogRequestBuilder"/></returns>
        /// <param name="pullZoneId">The path parameter: pullZoneId</param>
        public global::Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithPullZoneIdLog.WithPullZoneIdLogRequestBuilder WithPullZoneIdLog(long? pullZoneId)
        {
            if(ReferenceEquals(pullZoneId, null)) throw new ArgumentNullException(nameof(pullZoneId));
            return new global::Soenneker.Bunny.OpenApiClient.CdnLogging.Item.WithPullZoneIdLog.WithPullZoneIdLogRequestBuilder(PathParameters, RequestAdapter, pullZoneId);
        }
    }
}
#pragma warning restore CS0618
